# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneydonate',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('paypal_active', models.BooleanField(verbose_name=b'PayPal aktiv')),
                ('paypal_text', models.CharField(blank=True, max_length=255, verbose_name=b'Beschreibung PayPal')),
                ('onba_active', models.BooleanField(verbose_name=b'E-Banking aktiv')),
                ('onba_text', models.CharField(blank=True, max_length=255, verbose_name=b'Beschreibung E-Banking')),
                ('onba_account', models.CharField(blank=True, max_length=255, verbose_name=b'Kontonummer')),
                ('onba_recipient', models.CharField(blank=True, max_length=255, verbose_name=b'Empfaenger')),
                ('onba_iban', models.CharField(blank=True, max_length=255, verbose_name=b'IBAN')),
                ('onba_bic', models.CharField(blank=True, max_length=255, verbose_name=b'BIC')),
                ('invoice_active', models.BooleanField(verbose_name=b'Einzahlungsschein aktiv')),
                ('invoice_text', models.CharField(blank=True, max_length=255, verbose_name=b'Beschreibung Einzahlungsschein')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MoneydonateAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name=b'Beschreibung')),
                ('amount', models.IntegerField(verbose_name=b'Betrag')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Aktiv')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='moneydonate.Moneydonate')),
            ],
        ),
    ]
