# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneydonateamount',
            options={'verbose_name': 'Geldspendebetr\xe4ge'},
        ),
        migrations.AddField(
            model_name='moneydonate',
            name='paypal_cancel_url',
            field=models.TextField(blank=True, verbose_name=b'Abbruch URL'),
        ),
        migrations.AddField(
            model_name='moneydonate',
            name='paypal_return_url',
            field=models.TextField(blank=True, verbose_name=b'Weiterleitungsadresse'),
        ),
        migrations.AlterField(
            model_name='moneydonate',
            name='onba_recipient',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Empf\xc3\xa4nger'),
        ),
    ]
