# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonate', '0002_auto_20161018_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydonate',
            name='paypal_receiver_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name=b'PayPal Empf\xc3\xa4nger'),
        ),
    ]
