# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonate', '0003_moneydonate_paypal_receiver_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneydonate',
            name='invoice_text',
            field=models.TextField(blank=True, max_length=255, verbose_name=b'Beschreibung Einzahlungsschein'),
        ),
        migrations.AlterField(
            model_name='moneydonate',
            name='onba_text',
            field=models.TextField(blank=True, max_length=255, verbose_name=b'Beschreibung E-Banking'),
        ),
        migrations.AlterField(
            model_name='moneydonate',
            name='paypal_cancel_url',
            field=models.URLField(blank=True, verbose_name=b'Abbruch URL'),
        ),
        migrations.AlterField(
            model_name='moneydonate',
            name='paypal_return_url',
            field=models.URLField(blank=True, verbose_name=b'Weiterleitungsadresse'),
        ),
        migrations.AlterField(
            model_name='moneydonate',
            name='paypal_text',
            field=models.TextField(blank=True, verbose_name=b'Beschreibung PayPal'),
        ),
    ]
