# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonate', '0004_auto_20161018_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneydonate',
            name='paypal_receiver_mail',
        ),
    ]
