# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonate', '0005_remove_moneydonate_paypal_receiver_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Betrag')),
                ('empty_invoice', models.BooleanField(default=False, verbose_name=b'Leerer Einzahlungsschein')),
                ('number_invoices', models.IntegerField(default=1, verbose_name=b'Menge')),
                ('first_name', models.CharField(max_length=255, verbose_name=b'Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name=b'Nachname')),
                ('address', models.CharField(max_length=255, verbose_name=b'Adresse')),
                ('zip', models.CharField(max_length=255, verbose_name=b'PLZ, Ort')),
                ('comment', models.TextField(blank=True, verbose_name=b'Anmerkung')),
            ],
            options={
                'verbose_name': 'Einzahlungschein',
                'verbose_name_plural': 'Einzahlungsscheine',
            },
        ),
    ]
