# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonate', '0006_invoiceorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneydonateamount',
            options={'verbose_name': 'Geldspendebetrag', 'verbose_name_plural': 'Geldspendebetr\xe4ge'},
        ),
        migrations.RemoveField(
            model_name='moneydonate',
            name='paypal_cancel_url',
        ),
        migrations.RemoveField(
            model_name='moneydonate',
            name='paypal_return_url',
        ),
        migrations.AddField(
            model_name='moneydonate',
            name='return_url',
            field=models.URLField(default='localhost:8000', verbose_name=b'Weiterleitungs-URL'),
            preserve_default=False,
        ),
    ]
