# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name=b'Name des Fahrzeugs')),
                ('image', django_resized.forms.ResizedImageField(blank=True, help_text=b'Foto des Fahrzeugs', null=True, upload_to=b'stock/categories/')),
                ('plate', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Autokennzeichen')),
                ('organisation', models.ForeignKey(blank=True, help_text=b'Organisation welcher das Fahrzeug geh\xc3\xb6rt.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name des Fahrers')),
                ('active', models.BooleanField(default=True, help_text=b'Ist der Fahrer noch bei Velafrica? Inaktive Fahrer werden als (inaktiv) in der Auswahl bei den Fahrten aufgef\xc3\xbchrtgi.')),
                ('organisation', models.ForeignKey(blank=True, help_text=b'Organisation bei welcher der Fahrer angestellt ist.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCar',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name=b'Name des Fahrzeugs')),
                ('image', models.TextField(blank=True, help_text=b'Foto des Fahrzeugs', max_length=100, null=True)),
                ('plate', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Autokennzeichen')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical car',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDriver',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name des Fahrers')),
                ('active', models.BooleanField(default=True, help_text=b'Ist der Fahrer noch bei Velafrica? Inaktive Fahrer werden als (inaktiv) in der Auswahl bei den Fahrten aufgef\xc3\xbchrtgi.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical driver',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRide',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name=b'Datum')),
                ('from_warehouse_detail_address', models.TextField(blank=True, help_text=b'Bei Auswahl von "Diverse Spender" als Startpunkt, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name=b'FROM_WAREHOUSE alternative Adress (optional)')),
                ('to_warehouse_detail_address', models.TextField(blank=True, help_text=b'Bei Auswahl von "Diverse Spender" als Ziel, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name=b'TO_WAREHOUSE alternative Adress (optional)')),
                ('velos', models.IntegerField(default=0, verbose_name=b'Anzahl Velos')),
                ('spare_parts', models.BooleanField(default=False, verbose_name=b'Ersatzteile transportiert?')),
                ('note', models.CharField(blank=True, help_text=b'Bemerkung zur Fahrt', max_length=255, null=True, verbose_name=b'Bemerkung')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name=b'Ungef\xc3\xa4hre Distanz in Meter')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('car', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.Car')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.Driver')),
                ('from_warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stocklist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.StockList')),
                ('to_warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical ride',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVeloState',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Name des Zustandes')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Beschreibung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical velo state',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name=b'Datum')),
                ('from_warehouse_detail_address', models.TextField(blank=True, help_text=b'Bei Auswahl von "Diverse Spender" als Startpunkt, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name=b'FROM_WAREHOUSE alternative Adress (optional)')),
                ('to_warehouse_detail_address', models.TextField(blank=True, help_text=b'Bei Auswahl von "Diverse Spender" als Ziel, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name=b'TO_WAREHOUSE alternative Adress (optional)')),
                ('velos', models.IntegerField(default=0, verbose_name=b'Anzahl Velos')),
                ('spare_parts', models.BooleanField(default=False, verbose_name=b'Ersatzteile transportiert?')),
                ('note', models.CharField(blank=True, help_text=b'Bemerkung zur Fahrt', max_length=255, null=True, verbose_name=b'Bemerkung')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name=b'Ungef\xc3\xa4hre Distanz in Meter')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Car', verbose_name=b'Fahrzeug')),
                ('driver', models.ForeignKey(help_text=b'Person die den Transport durchgef\xc3\xbchrt hat.', on_delete=django.db.models.deletion.CASCADE, to='transport.Driver', verbose_name=b'Fahrer')),
                ('from_warehouse', models.ForeignKey(help_text=b'Start der Fahrt', on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='stock.Warehouse', verbose_name=b'Start')),
                ('stocklist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockList')),
                ('to_warehouse', models.ForeignKey(help_text=b'Ziel der Fahrt', on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='stock.Warehouse', verbose_name=b'Ziel')),
            ],
            options={
                'ordering': ['-date', 'from_warehouse'],
            },
        ),
        migrations.CreateModel(
            name='VeloState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name=b'Name des Zustandes')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Beschreibung')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='velo_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.VeloState', verbose_name=b'Zustand der Velos'),
        ),
        migrations.AddField(
            model_name='historicalride',
            name='velo_state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.VeloState'),
        ),
    ]
