# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Foto des Fahrzeugs', keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='stock/categories/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name des Fahrzeugs'),
        ),
        migrations.AlterField(
            model_name='car',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation welcher das Fahrzeug gehört.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autokennzeichen'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True, help_text='Ist der Fahrer noch bei Velafrica? Inaktive Fahrer werden als (inaktiv) in der Auswahl bei den Fahrten aufgeführtgi.'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name des Fahrers'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation bei welcher der Fahrer angestellt ist.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='image',
            field=models.TextField(blank=True, help_text='Foto des Fahrzeugs', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name des Fahrzeugs'),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organisation welcher das Fahrzeug gehört.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='plate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autokennzeichen'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='active',
            field=models.BooleanField(default=True, help_text='Ist der Fahrer noch bei Velafrica? Inaktive Fahrer werden als (inaktiv) in der Auswahl bei den Fahrten aufgeführtgi.'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name des Fahrers'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organisation bei welcher der Fahrer angestellt ist.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='car',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.Car', verbose_name='Fahrzeug'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ungefähre Distanz in Meter'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Person die den Transport durchgeführt hat.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.Driver', verbose_name='Fahrer'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Start der Fahrt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse', verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='from_warehouse_detail_address',
            field=models.TextField(blank=True, help_text='Bei Auswahl von "Diverse Spender" als Startpunkt, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name='FROM_WAREHOUSE alternative Adress (optional)'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='note',
            field=models.CharField(blank=True, help_text='Bemerkung zur Fahrt', max_length=255, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='spare_parts',
            field=models.BooleanField(default=False, verbose_name='Ersatzteile transportiert?'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ziel der Fahrt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse', verbose_name='Ziel'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='to_warehouse_detail_address',
            field=models.TextField(blank=True, help_text='Bei Auswahl von "Diverse Spender" als Ziel, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name='TO_WAREHOUSE alternative Adress (optional)'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='velo_state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.VeloState', verbose_name='Zustand der Velos'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='velos',
            field=models.IntegerField(default=0, verbose_name='Anzahl Velos'),
        ),
        migrations.AlterField(
            model_name='historicalvelostate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalvelostate',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalvelostate',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name des Zustandes'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Car', verbose_name='Fahrzeug'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ungefähre Distanz in Meter'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(help_text='Person die den Transport durchgeführt hat.', on_delete=django.db.models.deletion.CASCADE, to='transport.Driver', verbose_name='Fahrer'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_warehouse',
            field=models.ForeignKey(help_text='Start der Fahrt', on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='stock.Warehouse', verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_warehouse_detail_address',
            field=models.TextField(blank=True, help_text='Bei Auswahl von "Diverse Spender" als Startpunkt, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name='FROM_WAREHOUSE alternative Adress (optional)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='note',
            field=models.CharField(blank=True, help_text='Bemerkung zur Fahrt', max_length=255, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='spare_parts',
            field=models.BooleanField(default=False, verbose_name='Ersatzteile transportiert?'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_warehouse',
            field=models.ForeignKey(help_text='Ziel der Fahrt', on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='stock.Warehouse', verbose_name='Ziel'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_warehouse_detail_address',
            field=models.TextField(blank=True, help_text='Bei Auswahl von "Diverse Spender" als Ziel, kann hier optional die genaue Adresse eingetragen werden.', null=True, verbose_name='TO_WAREHOUSE alternative Adress (optional)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='velo_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.VeloState', verbose_name='Zustand der Velos'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='velos',
            field=models.IntegerField(default=0, verbose_name='Anzahl Velos'),
        ),
        migrations.AlterField(
            model_name='velostate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='velostate',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name des Zustandes'),
        ),
    ]
