# Generated by Django 2.1.12 on 2019-09-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20190326_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation bei welcher der Fahrer angestellt ist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='stocklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.StockList'),
        ),
    ]
