# Generated by Django 2.1.15 on 2020-01-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20191219_1147_squashed_0010_auto_20191231_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalride',
            name='to_contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel. Nr. (Mobile)'),
        ),
        migrations.AddField(
            model_name='ride',
            name='to_contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel. Nr. (Mobile)'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='charged',
            field=models.BooleanField(default=False, verbose_name='Kostenpflichtig?'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='created_by',
            field=models.CharField(default='', max_length=255, verbose_name='Auftrag erstellt von (Vor- und Nachname)'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel. Nr.'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Vereinbartes Abholdatum'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='from_comment',
            field=models.CharField(blank=True, default='', help_text='Details zum Abholstandort', max_length=255, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='from_contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel. Nr. (Mobile)'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='invoice_commissioned',
            field=models.BooleanField(default=False, help_text='Wird nur durch die zuständige Person von Velafrica ausgefüllt', verbose_name='Rechnung der Buchhaltung in Auftrag gegeben'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='invoice_same_as_customer',
            field=models.BooleanField(default=True, verbose_name='Rechnungsadresse = Kundenadresse'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='planned_velos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anzahl Velos (voraussichtlich)'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='request_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.RequestCategory', verbose_name='Kategorie Velospender'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='to_comment',
            field=models.CharField(blank=True, default='', help_text='Details zur Lieferadresse', max_length=255, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='velo_state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.VeloState', verbose_name='Transportgut'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='velos',
            field=models.IntegerField(blank=True, default=0, help_text='Wird durch den Transport ausgefüllt.', null=True, verbose_name='Anzahl transportierter Velos'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='charged',
            field=models.BooleanField(default=False, verbose_name='Kostenpflichtig?'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_by',
            field=models.CharField(default='', max_length=255, verbose_name='Auftrag erstellt von (Vor- und Nachname)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel. Nr.'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Vereinbartes Abholdatum'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_comment',
            field=models.CharField(blank=True, default='', help_text='Details zum Abholstandort', max_length=255, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel. Nr. (Mobile)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='invoice_commissioned',
            field=models.BooleanField(default=False, help_text='Wird nur durch die zuständige Person von Velafrica ausgefüllt', verbose_name='Rechnung der Buchhaltung in Auftrag gegeben'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='invoice_same_as_customer',
            field=models.BooleanField(default=True, verbose_name='Rechnungsadresse = Kundenadresse'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='planned_velos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anzahl Velos (voraussichtlich)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='request_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.RequestCategory', verbose_name='Kategorie Velospender'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_comment',
            field=models.CharField(blank=True, default='', help_text='Details zur Lieferadresse', max_length=255, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='velo_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.VeloState', verbose_name='Transportgut'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='velos',
            field=models.IntegerField(blank=True, default=0, help_text='Wird durch den Transport ausgefüllt.', null=True, verbose_name='Anzahl transportierter Velos'),
        ),
    ]
