# Generated by Django 2.1.15 on 2020-01-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20200108_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalride',
            name='cost_type',
            field=models.CharField(blank=True, default='3510-506', max_length=255, verbose_name='Kostenart und Kostenstelle'),
        ),
        migrations.AddField(
            model_name='historicalride',
            name='invoice_purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zweck'),
        ),
        migrations.AddField(
            model_name='ride',
            name='cost_type',
            field=models.CharField(blank=True, default='3510-506', max_length=255, verbose_name='Kostenart und Kostenstelle'),
        ),
        migrations.AddField(
            model_name='ride',
            name='invoice_purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zweck'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Betrag exkl. MWSt.'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Betrag exkl. MWSt.'),
        ),
    ]
