# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20160608_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='stocklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockList'),
        ),
    ]
