# Generated by Django 2.1.15 on 2020-01-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20200109_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vereinbarter Abholtermin'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vereinbarter Abholtermin'),
        ),
    ]
