# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20160608_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalride',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Ungef\xc3\xa4hre Distanz in Meter'),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Ungef\xc3\xa4hre Distanz in Meter'),
        ),
    ]
