# Generated by Django 2.1.15 on 2020-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20200110_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalride',
            name='pickup_time',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Vereinbarte Abholzeit'),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_time',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Vereinbarte Abholzeit'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Vereinbarter Abholtermin'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Vereinbarter Abholtermin'),
        ),
    ]
