# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20160729_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='person',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='person',
        ),
    ]
