# Generated by Django 2.1.15 on 2020-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20200122_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalride',
            name='printed',
            field=models.BooleanField(default=False, verbose_name='Auftrag gedruckt'),
        ),
        migrations.AddField(
            model_name='ride',
            name='printed',
            field=models.BooleanField(default=False, verbose_name='Auftrag gedruckt'),
        ),
    ]
