# Generated by Django 2.1.15 on 2020-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20200217_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='from_comment',
            field=models.CharField(blank=True, default='', help_text='Details zum Abholstandort', max_length=1024, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='note',
            field=models.CharField(blank=True, help_text='Bemerkung zum Fahrt', max_length=1024, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='request_comment',
            field=models.CharField(blank=True, default='', help_text='Bemerkung zum Auftrag', max_length=1024, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='to_comment',
            field=models.CharField(blank=True, default='', help_text='Details zur Lieferadresse', max_length=1024, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_comment',
            field=models.CharField(blank=True, default='', help_text='Details zum Abholstandort', max_length=1024, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='note',
            field=models.CharField(blank=True, help_text='Bemerkung zum Fahrt', max_length=1024, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='request_comment',
            field=models.CharField(blank=True, default='', help_text='Bemerkung zum Auftrag', max_length=1024, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_comment',
            field=models.CharField(blank=True, default='', help_text='Details zur Lieferadresse', max_length=1024, verbose_name='Details Standort'),
        ),
    ]
