# Generated by Django 2.1.15 on 2020-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20200221_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='from_comment',
            field=models.TextField(blank=True, default='', help_text='Details zum Abholstandort', max_length=1024, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='to_comment',
            field=models.TextField(blank=True, default='', help_text='Details zur Lieferadresse', max_length=1024, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_comment',
            field=models.TextField(blank=True, default='', help_text='Details zum Abholstandort', max_length=1024, verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_comment',
            field=models.TextField(blank=True, default='', help_text='Details zur Lieferadresse', max_length=1024, verbose_name='Details Standort'),
        ),
    ]
