# Generated by Django 2.1.15 on 2020-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20200324_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='from_comment',
            field=models.TextField(blank=True, default='', help_text='Details zum Abholstandort', verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='note',
            field=models.TextField(blank=True, help_text='Bemerkung zum Fahrt', null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='request_comment',
            field=models.TextField(blank=True, default='', help_text='Bemerkung zum Auftrag', verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_comment',
            field=models.TextField(blank=True, default='', help_text='Details zum Abholstandort', verbose_name='Details Standort'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='note',
            field=models.TextField(blank=True, help_text='Bemerkung zum Fahrt', null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='request_comment',
            field=models.TextField(blank=True, default='', help_text='Bemerkung zum Auftrag', verbose_name='Bemerkung'),
        ),
    ]
