# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20170729_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True, help_text=b'Ist der Fahrer noch bei Velafrica? Nur aktive Fahrer werden im Dropdown bei den Fahrten angezeigt.'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='active',
            field=models.BooleanField(default=True, help_text=b'Ist der Fahrer noch bei Velafrica? Nur aktive Fahrer werden im Dropdown bei den Fahrten angezeigt.'),
        ),
    ]
