# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_auto_20170929_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True, help_text=b'Ist der Fahrer noch bei Velafrica? Inaktive Fahrer werden als (inaktiv) in der Auswahl bei den Fahrten aufgef\xc3\xbchrtgi.'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='active',
            field=models.BooleanField(default=True, help_text=b'Ist der Fahrer noch bei Velafrica? Inaktive Fahrer werden als (inaktiv) in der Auswahl bei den Fahrten aufgef\xc3\xbchrtgi.'),
        ),
    ]
