# Generated by Django 2.1.15 on 2020-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transport', '0013_add_help_text_to_invoice_same_as_customer_field_20200527_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='planned_velos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Velos (angemeldet)'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='velos',
            field=models.IntegerField(blank=True, default=0, help_text='Wird durch den Transport ausgefüllt.',
                                      null=True, verbose_name='Velos (abgeholt)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='planned_velos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Velos (angemeldet)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='velos',
            field=models.IntegerField(blank=True, default=0, help_text='Wird durch den Transport ausgefüllt.',
                                      null=True, verbose_name='Velos (abgeholt)'),
        ),
    ]
