# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingstation',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
