# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 15:57
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0002_auto_20161012_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingstationquery',
            name='event_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Testeventtype')], max_length=1),
        ),
    ]
