# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0004_remove_trackingstationquery_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingstationquery',
            name='event_types',
            field=models.CharField(default='', max_length=255, verbose_name=b'Event Typen'),
            preserve_default=False,
        ),
    ]
