# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0005_trackingstationquery_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingstationquery',
            name='plugin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='cms_plugins.TrackingStation'),
            preserve_default=False,
        ),
    ]
