# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import multiselectfield.db.fields
import velafrica.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='arrival_partner_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ankunft Partner'),
        ),
        migrations.AlterField(
            model_name='container',
            name='arrival_port_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ankunft Hafen Partner'),
        ),
        migrations.AlterField(
            model_name='container',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Containernummer'),
        ),
        migrations.AlterField(
            model_name='container',
            name='logistics',
            field=models.ForeignKey(blank=True, help_text='Logistikunternehmen', null=True, on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Forwarder', verbose_name='Forwarder'),
        ),
        migrations.AlterField(
            model_name='container',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen zum Container'),
        ),
        migrations.AlterField(
            model_name='container',
            name='organisation_from',
            field=models.ForeignKey(blank=True, help_text='Ort wo der Container geladen wurde.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name='Verarbeitungspartner'),
        ),
        migrations.AlterField(
            model_name='container',
            name='partner_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.PartnerSud', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='container',
            name='pickup_date',
            field=models.DateField(verbose_name='Ladedatum'),
        ),
        migrations.AlterField(
            model_name='container',
            name='seal_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plombennummer'),
        ),
        migrations.AlterField(
            model_name='container',
            name='sgs_certified',
            field=models.BooleanField(default=False, verbose_name='SGS zertifiziert?'),
        ),
        migrations.AlterField(
            model_name='container',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Verschiffungsdatum ab Europa'),
        ),
        migrations.AlterField(
            model_name='container',
            name='spare_parts',
            field=models.BooleanField(default=False, verbose_name='Ersatzteile transportiert?'),
        ),
        migrations.AlterField(
            model_name='container',
            name='spare_parts_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='container',
            name='time_to_customer',
            field=models.IntegerField(blank=True, help_text='Anzahl Tage vom Verlad bis zur Ankunft beim Partner.', null=True, verbose_name='Versandzeit (Tage)'),
        ),
        migrations.AlterField(
            model_name='container',
            name='tools_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Werkzeuge'),
        ),
        migrations.AlterField(
            model_name='container',
            name='various_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Anderes'),
        ),
        migrations.AlterField(
            model_name='container',
            name='velos_loaded',
            field=models.IntegerField(default=0, verbose_name='Anzahl Velos eingeladen'),
        ),
        migrations.AlterField(
            model_name='container',
            name='velos_unloaded',
            field=models.IntegerField(default=0, verbose_name='Anzahl Velos ausgeladen'),
        ),
        migrations.AlterField(
            model_name='container',
            name='velos_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Velos'),
        ),
        migrations.AlterField(
            model_name='container',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, help_text='Lager wo die Velos verladen wurden', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse', verbose_name='Export Lager'),
        ),
        migrations.AlterField(
            model_name='forwarder',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name des Forwarders'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='arrival_partner_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ankunft Partner'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='arrival_port_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ankunft Hafen Partner'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='container_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Containernummer'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='logistics',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Logistikunternehmen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='velafrica_sud.Forwarder', verbose_name='Forwarder'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen zum Container'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='organisation_from',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ort wo der Container geladen wurde.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation', verbose_name='Verarbeitungspartner'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='partner_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='velafrica_sud.PartnerSud', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='pickup_date',
            field=models.DateField(verbose_name='Ladedatum'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='seal_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plombennummer'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='sgs_certified',
            field=models.BooleanField(default=False, verbose_name='SGS zertifiziert?'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Verschiffungsdatum ab Europa'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='spare_parts',
            field=models.BooleanField(default=False, verbose_name='Ersatzteile transportiert?'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='spare_parts_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='time_to_customer',
            field=models.IntegerField(blank=True, help_text='Anzahl Tage vom Verlad bis zur Ankunft beim Partner.', null=True, verbose_name='Versandzeit (Tage)'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='tools_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Werkzeuge'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='various_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Anderes'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='velos_loaded',
            field=models.IntegerField(default=0, verbose_name='Anzahl Velos eingeladen'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='velos_unloaded',
            field=models.IntegerField(default=0, verbose_name='Anzahl Velos ausgeladen'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='velos_worth',
            field=models.IntegerField(default=0, verbose_name='Wert Velos'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lager wo die Velos verladen wurden', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse', verbose_name='Export Lager'),
        ),
        migrations.AlterField(
            model_name='historicalforwarder',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalforwarder',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name des Forwarders'),
        ),
        migrations.AlterField(
            model_name='historicalpartnerstaff',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalpartnerstaff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name des Angestellten'),
        ),
        migrations.AlterField(
            model_name='historicalpartnerstaff',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='velafrica_sud.PartnerSud', verbose_name='Arbeitgeber'),
        ),
        migrations.AlterField(
            model_name='historicalpartnerstaff',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='velafrica_sud.Role', verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='image',
            field=models.TextField(blank=True, help_text='Foto vom Partner vor Ort.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='infrastructure',
            field=models.TextField(blank=True, help_text='Übersicht über die Infrastruktur vor Ort (Anzahl Arbeitsplätze, Lagermöglichkeiten, Art der Gebäude etc)', null=True, verbose_name='Infrastruktur'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='legalform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisationsform'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='partner_since',
            field=models.IntegerField(blank=True, help_text='Jahr', null=True, verbose_name='Partner seit...'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='vocational_training',
            field=models.BooleanField(default=False, verbose_name='Bietet Berufsbildung an'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_areas',
            field=models.CharField(blank=True, choices=[('education', 'Schooling / Education'), ('entrepreneurship', 'Entrepreneuership'), ('environment', 'Evnironment / Environmental protection'), ('mobility', 'Mobility'), ('women_empowerment', "Women's empowerment"), ('children_empowerment', "Children's empowerment"), ('sports_activist', 'Sports activities'), ('other', 'Other')], max_length=1, null=True, verbose_name='Feld der Community Arbeit'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_manager',
            field=models.BooleanField(default=False, verbose_name='Community Manager vorhanden?'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anzahl Personen die vom Community Projekt profitiert haben'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_reinvest_profit',
            field=models.BooleanField(default=False, verbose_name='Gewinn vom letzten Jahr in Community Projekte investiert?'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_reinvest_profit_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='In Community Projekt re-investierter Betrag'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Allgemeine Kommentare zur Partnerschaft'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_ordering_experience',
            field=models.TextField(blank=True, help_text='Wie wird das Bestellen der Fahrräder und Ersatzteile empfunden?', null=True, verbose_name='Bestellerlebnis'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_quality_bicycles',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Qualität der gelieferten Velos'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_quality_spares',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Qualität der gelieferten Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_quality_tools',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Qualität der gelieferten Werkzeuge'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='currency',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Verwendete Währung bei Finanzangaben'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Währungskurs zu USD'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_bicycles_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl verkaufte Fahrräder'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_bicycles_turnover',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umsatz Fahrräder'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category1_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 1'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category1_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 1'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category2_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 2'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category2_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 2'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category3_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 3'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category3_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 3'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category4_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 4'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category4_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 4'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category5_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 5'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category5_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 5'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category6_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 6'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category6_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 6'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category7_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 7'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category7_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 7'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category8_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 8'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_category8_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 8'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_import_taxes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aktuelle Importzölle für gebrauchte Fahrräder'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_payment_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cash', 'Cash Payment'), ('installment', 'Installment'), ('card', 'Payment with Credit/Debit Card'), ('phone', 'Payment with Mobile Phone'), ('microloan', 'Micro Loan (e.g. in cooperation with Micro Finance Institution)'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_services_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl verkaufte Dienstleistungen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_services_turnover',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umsatz Dienstleistungen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_spareparts_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl verkaufte Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_spareparts_turnover',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umsatz Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_transport_costs_port_to_organisation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aktuelle Kosten für Transport von Eingangshafen zur Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_turnover_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Umsatz'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_fulltime_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Vollzeit Männer'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_fulltime_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Vollzeit Frauen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_internship_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Internship Männer'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_internship_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Internship Frauen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Jobs Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_parttime_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Teilzeit Männer'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_parttime_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Teilzeit Frauen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_salary_calculation',
            field=models.TextField(blank=True, help_text='Wie werden die Saläre / Kompensationen berechnet?', null=True, verbose_name='Berechnung der Saläre'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_trainee_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Trainee Männer'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_trainee_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Trainee Frauen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_volunteer_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Freiwillige Männer'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_volunteer_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Freiwillige Frauen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='final_biggest_success',
            field=models.TextField(blank=True, null=True, verbose_name='Grösste Erfolge dieses Jahres?'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='final_future_challenges',
            field=models.TextField(blank=True, null=True, verbose_name='Grösste Herausforderungen der Zukunft?'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_event_attendance',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_event_organisation',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_flyer',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_mouth',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_other',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_poster',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_radio',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_socialmedia',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_tv',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_customer_segments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_customer_segments_other',
            field=models.CharField(blank=True, help_text="Bitte ausfüllen, wenn bei der vorherigen Frage 'others' ausgewählt wurde.", max_length=255, null=True, verbose_name='Andere'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_customer_segments_top1',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente Top 1'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_customer_segments_top2',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente Top 2'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_customer_segments_top3',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente Top 3'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Andere'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Retail'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Wholesale'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='mobilityprogram_financial_support',
            field=models.BooleanField(default=False, verbose_name='Mobilitätsprogramm finanziell von Velafrica unterstützt?'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='mobilityprogram_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='mobilityprogram_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anzahl Personen die vom Mobilitätsprogramm profitiert haben'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_certificates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ausgestellte Zertifikate dieses Jahr'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_certificates_ack',
            field=models.IntegerField(blank=True, null=True, verbose_name='Davon staatlich anerkannte Zertifikate'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_completed_boys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Jungen Ausbildungsprogramm abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_completed_girls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Mädchen Ausbildungsprogramm abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_exstudents_agriculture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt in der Landwirtschaft arbeiten'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_exstudents_bicycle_industry',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt im Velogewerbe arbeiten'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_exstudents_employed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Studenten vom letzten Jahr die jetzt angestellt sind'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_exstudents_energy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt im Energie Sektor arbeiten'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_exstudents_familiybusiness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt im Familienbetrieb arbeiten'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_exstudents_selfemployed_link',
            field=models.IntegerField(blank=True, null=True, verbose_name='Studenten vom letzten Jahr die jetzt bei einem Partnerbetrieb angestellt sind'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_exstudents_selfemployed_new',
            field=models.IntegerField(blank=True, null=True, verbose_name='Studenten vom letzten Jahr die jetzt bei einem anderen Betrieb angestellt sind'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_program_boys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Jungen im Ausbildungsprogramm'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_program_duration',
            field=models.CharField(blank=True, choices=[('less_than_3_months', 'less than 3 months'), ('6_to_12_months', '6 - 12 months'), ('12_to_18_months', '12 - 18 months'), ('18_to_24_months', '18 - 24 months'), ('more_than_24_months', 'more than 24 months')], max_length=1, null=True, verbose_name='Dauer des Beschäftigungsprogramms'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_program_girls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Mädchen im Ausbildungsprogramm'),
        ),
        migrations.AlterField(
            model_name='historicalreportstaff',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalreportstaff',
            name='number',
            field=models.IntegerField(verbose_name='Anzahl Angestellte'),
        ),
        migrations.AlterField(
            model_name='historicalreportstaff',
            name='report',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='velafrica_sud.Report', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='historicalreportstaff',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='velafrica_sud.Role', verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='historicalreportstaff',
            name='salary',
            field=models.IntegerField(verbose_name='Salär (USD)'),
        ),
        migrations.AlterField(
            model_name='partnerstaff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name des Angestellten'),
        ),
        migrations.AlterField(
            model_name='partnerstaff',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.PartnerSud', verbose_name='Arbeitgeber'),
        ),
        migrations.AlterField(
            model_name='partnerstaff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Role', verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Foto vom Partner vor Ort.', keep_meta=True, null=True, quality=75, size=[800, 800], storage=velafrica.core.storage.MyStorage(), upload_to='velafrica_sud/partner/'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='infrastructure',
            field=models.TextField(blank=True, help_text='Übersicht über die Infrastruktur vor Ort (Anzahl Arbeitsplätze, Lagermöglichkeiten, Art der Gebäude etc)', null=True, verbose_name='Infrastruktur'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='legalform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisationsform'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='partner_since',
            field=models.IntegerField(blank=True, help_text='Jahr', null=True, verbose_name='Partner seit...'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='vocational_training',
            field=models.BooleanField(default=False, verbose_name='Bietet Berufsbildung an'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_areas',
            field=models.CharField(blank=True, choices=[('education', 'Schooling / Education'), ('entrepreneurship', 'Entrepreneuership'), ('environment', 'Evnironment / Environmental protection'), ('mobility', 'Mobility'), ('women_empowerment', "Women's empowerment"), ('children_empowerment', "Children's empowerment"), ('sports_activist', 'Sports activities'), ('other', 'Other')], max_length=1, null=True, verbose_name='Feld der Community Arbeit'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_manager',
            field=models.BooleanField(default=False, verbose_name='Community Manager vorhanden?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anzahl Personen die vom Community Projekt profitiert haben'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_reinvest_profit',
            field=models.BooleanField(default=False, verbose_name='Gewinn vom letzten Jahr in Community Projekte investiert?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_reinvest_profit_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='In Community Projekt re-investierter Betrag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Allgemeine Kommentare zur Partnerschaft'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_ordering_experience',
            field=models.TextField(blank=True, help_text='Wie wird das Bestellen der Fahrräder und Ersatzteile empfunden?', null=True, verbose_name='Bestellerlebnis'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_quality_bicycles',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Qualität der gelieferten Velos'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_quality_spares',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Qualität der gelieferten Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_quality_tools',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Qualität der gelieferten Werkzeuge'),
        ),
        migrations.AlterField(
            model_name='report',
            name='currency',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Verwendete Währung bei Finanzangaben'),
        ),
        migrations.AlterField(
            model_name='report',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Währungskurs zu USD'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_bicycles_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl verkaufte Fahrräder'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_bicycles_turnover',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umsatz Fahrräder'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category1_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category1_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category2_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category2_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category3_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category3_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category4_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category4_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category5_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 5'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category5_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 5'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category6_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 6'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category6_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 6'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category7_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 7'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category7_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 7'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category8_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie 8'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_category8_pricerange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preisrange Kategorie 8'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_import_taxes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aktuelle Importzölle für gebrauchte Fahrräder'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_payment_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cash', 'Cash Payment'), ('installment', 'Installment'), ('card', 'Payment with Credit/Debit Card'), ('phone', 'Payment with Mobile Phone'), ('microloan', 'Micro Loan (e.g. in cooperation with Micro Finance Institution)'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_services_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl verkaufte Dienstleistungen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_services_turnover',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umsatz Dienstleistungen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_spareparts_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl verkaufte Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_spareparts_turnover',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umsatz Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_transport_costs_port_to_organisation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aktuelle Kosten für Transport von Eingangshafen zur Organisation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_turnover_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Umsatz'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_fulltime_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Vollzeit Männer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_fulltime_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Vollzeit Frauen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_internship_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Internship Männer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_internship_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Internship Frauen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Jobs Beschreibung'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_parttime_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Teilzeit Männer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_parttime_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Teilzeit Frauen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_salary_calculation',
            field=models.TextField(blank=True, help_text='Wie werden die Saläre / Kompensationen berechnet?', null=True, verbose_name='Berechnung der Saläre'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_trainee_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Trainee Männer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_trainee_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Trainee Frauen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_volunteer_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Freiwillige Männer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_volunteer_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angestellte Freiwillige Frauen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='final_biggest_success',
            field=models.TextField(blank=True, null=True, verbose_name='Grösste Erfolge dieses Jahres?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='final_future_challenges',
            field=models.TextField(blank=True, null=True, verbose_name='Grösste Herausforderungen der Zukunft?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_event_attendance',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_event_organisation',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_flyer',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_mouth',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_other',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_poster',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_radio',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_socialmedia',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_tv',
            field=models.CharField(blank=True, choices=[('not_using_it', "We don't use it"), ('rarely', 'rarely'), ('occasionally', 'occasionally'), ('often', 'often'), ('very often', 'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_customer_segments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_customer_segments_other',
            field=models.CharField(blank=True, help_text="Bitte ausfüllen, wenn bei der vorherigen Frage 'others' ausgewählt wurde.", max_length=255, null=True, verbose_name='Andere'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_customer_segments_top1',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente Top 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_customer_segments_top2',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente Top 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_customer_segments_top3',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('children_students', 'Children/Students'), ('teachers', 'Teachers'), ('businessmen', 'Business Men'), ('retail', 'Bicycle Retail Agents'), ('wholesale', 'Bicycle Wholesale Agents'), ('farmers', 'Farmers'), ('safari', 'Safari companies'), ('hospitals', 'Hospitals'), ('other', 'other')], max_length=255, null=True, verbose_name='Kundensegmente Top 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Andere'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Retail'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[('not_good', 'not good'), ('ok', 'ok'), ('successful', 'successful'), ('not_using_it_yet', 'we do not use it (yet)')], max_length=1, null=True, verbose_name='Wholesale'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mobilityprogram_financial_support',
            field=models.BooleanField(default=False, verbose_name='Mobilitätsprogramm finanziell von Velafrica unterstützt?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mobilityprogram_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mobilityprogram_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anzahl Personen die vom Mobilitätsprogramm profitiert haben'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_certificates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ausgestellte Zertifikate dieses Jahr'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_certificates_ack',
            field=models.IntegerField(blank=True, null=True, verbose_name='Davon staatlich anerkannte Zertifikate'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_completed_boys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Jungen Ausbildungsprogramm abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_completed_girls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Mädchen Ausbildungsprogramm abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_exstudents_agriculture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt in der Landwirtschaft arbeiten'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_exstudents_bicycle_industry',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt im Velogewerbe arbeiten'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_exstudents_employed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Studenten vom letzten Jahr die jetzt angestellt sind'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_exstudents_energy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt im Energie Sektor arbeiten'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_exstudents_familiybusiness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Ex-Studenten die jetzt im Familienbetrieb arbeiten'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_exstudents_selfemployed_link',
            field=models.IntegerField(blank=True, null=True, verbose_name='Studenten vom letzten Jahr die jetzt bei einem Partnerbetrieb angestellt sind'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_exstudents_selfemployed_new',
            field=models.IntegerField(blank=True, null=True, verbose_name='Studenten vom letzten Jahr die jetzt bei einem anderen Betrieb angestellt sind'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_program_boys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Jungen im Ausbildungsprogramm'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_program_duration',
            field=models.CharField(blank=True, choices=[('less_than_3_months', 'less than 3 months'), ('6_to_12_months', '6 - 12 months'), ('12_to_18_months', '12 - 18 months'), ('18_to_24_months', '18 - 24 months'), ('more_than_24_months', 'more than 24 months')], max_length=1, null=True, verbose_name='Dauer des Beschäftigungsprogramms'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_program_girls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Mädchen im Ausbildungsprogramm'),
        ),
        migrations.AlterField(
            model_name='reportstaff',
            name='number',
            field=models.IntegerField(verbose_name='Anzahl Angestellte'),
        ),
        migrations.AlterField(
            model_name='reportstaff',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Report', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='reportstaff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Role', verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='reportstaff',
            name='salary',
            field=models.IntegerField(verbose_name='Salär (USD)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
