# Generated by Django 2.1.12 on 2019-09-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0002_auto_20190326_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='logistics',
            field=models.ForeignKey(blank=True, help_text='Logistikunternehmen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='velafrica_sud.Forwarder', verbose_name='Forwarder'),
        ),
    ]
