# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0010_auto_20160329_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnersud',
            options={'ordering': ['name'], 'verbose_name_plural': 'Partner S\xfcd'},
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='area',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='legalform',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=b'Organisationsform'),
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='org_type',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='partner_since',
            field=models.IntegerField(blank=True, help_text=b'Jahr', null=True, verbose_name=b'Partner seit...'),
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='street',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='area',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='legalform',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=b'Organisationsform'),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='org_type',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='partner_since',
            field=models.IntegerField(blank=True, help_text=b'Jahr', null=True, verbose_name=b'Partner seit...'),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='street',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
