# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0012_auto_20160601_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website'),
        ),
    ]
