# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0013_auto_20160601_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
    ]
