# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20160601_1344'),
        ('velafrica_sud', '0014_auto_20160602_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='stocklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockList'),
        ),
        migrations.AddField(
            model_name='historicalcontainer',
            name='stocklist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.StockList'),
        ),
    ]
