# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0015_auto_20160608_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='stocklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockList'),
        ),
    ]
