# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0017_auto_20160609_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='logistics',
            field=models.ForeignKey(blank=True, help_text=b'Logistikunternehmen', null=True, on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Forwarder', verbose_name=b'Forwarder'),
        ),
    ]
