# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 11:25
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0019_auto_20160628_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(default=django.utils.timezone.now)),
                ('employment_fulltime_men', models.IntegerField(verbose_name=b'Angestellte Vollzeit M\xc3\xa4nner')),
                ('employment_fulltime_women', models.IntegerField(verbose_name=b'Angestellte Vollzeit Frauen')),
                ('employment_parttime_men', models.IntegerField(verbose_name=b'Angestellte Teilzeit M\xc3\xa4nner')),
                ('employment_volunteer_men', models.IntegerField(verbose_name=b'Angestellte Freiwillige M\xc3\xa4nner')),
                ('employment_parttime_women', models.IntegerField(verbose_name=b'Angestellte Freiwillige Frauen')),
                ('employment_internship_men', models.IntegerField(verbose_name=b'Angestellte Internship M\xc3\xa4nner')),
                ('employment_internship_women', models.IntegerField(verbose_name=b'Angestellte Internship Frauen')),
                ('employment_trainee_men', models.IntegerField(verbose_name=b'Angestellte Trainee M\xc3\xa4nner')),
                ('employment_trainee_women', models.IntegerField(verbose_name=b'Angestellte Trainee Frauen')),
                ('economic_bicycles_amount', models.IntegerField(verbose_name=b'Anzahl verkaufte Fahrr\xc3\xa4der')),
                ('economic_bicycles_turnover', models.IntegerField(verbose_name=b'Umsatz Fahrr\xc3\xa4der')),
                ('economic_spareparts_amount', models.IntegerField(verbose_name=b'Anzahl verkaufte Ersatzteile')),
                ('economic_spareparts_turnover', models.IntegerField(verbose_name=b'Umsatz Ersatzteile')),
                ('economic_services_amount', models.IntegerField(verbose_name=b'Anzahl verkaufte Dienstleistungen')),
                ('economic_services_turnover', models.IntegerField(verbose_name=b'Umsatz Dienstleistungen')),
                ('economic_turnover_total', models.IntegerField(verbose_name=b'Total Umsatz')),
                ('economic_category1_name', models.CharField(max_length=255, verbose_name=b'Kategorie 1')),
                ('economic_category1_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 1')),
                ('economic_category2_name', models.CharField(max_length=255, verbose_name=b'Kategorie 2')),
                ('economic_category2_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 2')),
                ('economic_category3_name', models.CharField(max_length=255, verbose_name=b'Kategorie 3')),
                ('economic_category3_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 3')),
                ('economic_category4_name', models.CharField(max_length=255, verbose_name=b'Kategorie 4')),
                ('economic_category4_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 4')),
                ('economic_category5_name', models.CharField(max_length=255, verbose_name=b'Kategorie 5')),
                ('economic_category5_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 5')),
                ('economic_category6_name', models.CharField(max_length=255, verbose_name=b'Kategorie 6')),
                ('economic_category6_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 6')),
                ('economic_category7_name', models.CharField(max_length=255, verbose_name=b'Kategorie 7')),
                ('economic_category7_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 7')),
                ('economic_category8_name', models.CharField(max_length=255, verbose_name=b'Kategorie 8')),
                ('economic_category8_pricerange', models.CharField(max_length=255, verbose_name=b'Preisrange Kategorie 8')),
                ('economic_payment_types', models.CharField(choices=[(b'cash', b'Cash Payment'), (b'installment', b'Installment'), (b'card', b'Payment with Credit/Debit Card'), (b'phone', b'Payment with Mobile Phone'), (b'microloan', b'Micro Loan (e.g. in cooperation with Micro Finance Institution)'), (b'other', b'Other')], max_length=20)),
                ('vocational_program_duration', models.CharField(choices=[(b'0', b'less than 3 months'), (b'1', b'6 - 12 months'), (b'2', b'12 - 18 months'), (b'3', b'18 - 24 months'), (b'4', b'more than 24 months')], max_length=1)),
                ('vocational_program_girls', models.IntegerField(verbose_name=b'Anzahl M\xc3\xa4dchen im Ausbildungsprogramm')),
                ('vocational_program_boys', models.IntegerField(verbose_name=b'Anzahl Jungen im Ausbildungsprogramm')),
                ('vocational_completed_girls', models.IntegerField(verbose_name=b'Anzahl M\xc3\xa4dchen Ausbildungsprogramm abgeschlossen')),
                ('vocational_completed_boys', models.IntegerField(verbose_name=b'Anzahl Jungen Ausbildungsprogramm abgeschlossen')),
                ('vocational_exstudents_employed', models.IntegerField(verbose_name=b'Studenten vom letzten Jahr die jetzt angestellt sind')),
                ('vocational_exstudents_selfemployed_new', models.IntegerField(verbose_name=b'Studenten vom letzten Jahr die jetzt bei einem anderen Betrieb angestellt sind')),
                ('vocational_exstudents_selfemployed_link', models.IntegerField(verbose_name=b'Studenten vom letzten Jahr die jetzt bei einem Partnerbetrieb angestellt sind')),
                ('mobilityprogram', models.BooleanField(default=False)),
                ('mobilityprogram_people_benefitted', models.IntegerField(verbose_name=b'Number of people that benefitted from mobility programm')),
                ('mobilityprogram_financial_support', models.BooleanField(default=False, verbose_name=b'Mobilit\xc3\xa4tsprogramm finanziell von Velafrica unterst\xc3\xbctzt?')),
                ('communityproject_reinvest_profit', models.BooleanField(default=False, verbose_name=b'Gewinn vom letzten Jahr in Community Projekte investiert?')),
                ('communityproject_areas', models.CharField(choices=[(b'0', b'Schooling / Education'), (b'1', b'Entrepreneuership'), (b'2', b'Evnironment / Environmental protection'), (b'3', b'Mobility'), (b'4', b"Women's empowerment"), (b'5', b"Children's empowerment"), (b'6', b'Sports activities'), (b'7', b'Other')], max_length=1, verbose_name=b'Feld der Gemeinschaftsarbeit')),
                ('communityproject_reinvest_profit_total', models.IntegerField(verbose_name=b'In Gemeinschaftsprojekte re-investierter Betrag')),
                ('communityproject_people_benefitted', models.CharField(max_length=255, verbose_name=b'Anzahl Personen die profitiert haben vom Gemeinschaftsprojekt')),
                ('partner_sud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.PartnerSud')),
            ],
            options={
                'ordering': ['-creation'],
            },
        ),
    ]
