# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0020_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='employment_volunteer_women',
            field=models.IntegerField(default=0, verbose_name=b'Angestellte Freiwillige Frauen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_parttime_women',
            field=models.IntegerField(verbose_name=b'Angestellte Teilzeit Frauen'),
        ),
    ]
