# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0025_auto_20160719_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnersud',
            name='infrastructure',
            field=models.TextField(blank=True, help_text=b'\xc3\x9cbersicht \xc3\xbcber die Infrastruktur vor Ort (Anzahl Arbeitspl\xc3\xa4tze, Lagerm\xc3\xb6glichkeiten, Art der Geb\xc3\xa4ude etc)', null=True, verbose_name=b'Infrastruktur'),
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='vocational_training',
            field=models.BooleanField(default=False, verbose_name=b'Bietet Berufsbildung an'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='economic_import_taxes',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Aktuelle Importz\xc3\xb6lle f\xc3\xbcr gebrauchte Fahrr\xc3\xa4der'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='economic_transport_costs_port_to_organisation',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Aktuelle Kosten f\xc3\xbcr Transport von Eingangshafen zur Organisation'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='employment_salary_calculation',
            field=models.TextField(blank=True, help_text=b'Wie werden die Sal\xc3\xa4re / Kompensationen berechnet?', null=True, verbose_name=b'Berechnung der Sal\xc3\xa4re'),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='infrastructure',
            field=models.TextField(blank=True, help_text=b'\xc3\x9cbersicht \xc3\xbcber die Infrastruktur vor Ort (Anzahl Arbeitspl\xc3\xa4tze, Lagerm\xc3\xb6glichkeiten, Art der Geb\xc3\xa4ude etc)', null=True, verbose_name=b'Infrastruktur'),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='vocational_training',
            field=models.BooleanField(default=False, verbose_name=b'Bietet Berufsbildung an'),
        ),
        migrations.AddField(
            model_name='report',
            name='economic_import_taxes',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Aktuelle Importz\xc3\xb6lle f\xc3\xbcr gebrauchte Fahrr\xc3\xa4der'),
        ),
        migrations.AddField(
            model_name='report',
            name='economic_transport_costs_port_to_organisation',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Aktuelle Kosten f\xc3\xbcr Transport von Eingangshafen zur Organisation'),
        ),
        migrations.AddField(
            model_name='report',
            name='employment_salary_calculation',
            field=models.TextField(blank=True, help_text=b'Wie werden die Sal\xc3\xa4re / Kompensationen berechnet?', null=True, verbose_name=b'Berechnung der Sal\xc3\xa4re'),
        ),
    ]
