# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0026_auto_20160720_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnersud',
            name='contact',
            field=models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='communityproject_manager',
            field=models.BooleanField(default=False, verbose_name=b'Community Manager vorhanden?'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='cooperation_comments',
            field=models.TextField(blank=True, null=True, verbose_name=b'Allgemeine Kommentare zur Partnerschaft'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='cooperation_ordering_experience',
            field=models.TextField(blank=True, help_text=b'Wie wird das Bestellen der Fahrr\xc3\xa4der und Ersatzteile empfunden?', null=True, verbose_name=b'Bestell Erlebnis'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='cooperation_quality_bicycles',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='cooperation_quality_spares',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='cooperation_quality_tools',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='final_biggest_success',
            field=models.TextField(blank=True, null=True, verbose_name=b'Gr\xc3\xb6sste Erfolge dieses Jahres?'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='final_future_challenges',
            field=models.TextField(blank=True, null=True, verbose_name=b'Gr\xc3\xb6sste Herausforderungen der Zukunft?'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_event_attendance',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_event_organisation',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_flyer',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_mouth',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_other',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_poster',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_radio',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_socialmedia',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_channels_tv',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_customer_segments',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_customer_segments_other',
            field=models.CharField(blank=True, help_text=b"Bitte ausf\xc3\xbcllen, wenn bei der vorherigen Frage 'others' ausgew\xc3\xa4hlt wurde.", max_length=255, null=True, verbose_name=b'Andere'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_customer_segments_top3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 3'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='vocational_certificates',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Ausgestellte Zertifikate dieses Jahr'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='vocational_certificates_ack',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Davon staatlich anerkannte Zertifikate'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='vocational_exstudents_agriculture',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt in der Landwirtschaft arbeiten'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='vocational_exstudents_bicycle_industry',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt im Velogewerbe arbeiten'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='vocational_exstudents_energy',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt im Energie Sektor arbeiten'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='vocational_exstudents_familiybusiness',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt im Familienbetrieb arbeiten'),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='contact',
            field=models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson'),
        ),
        migrations.AddField(
            model_name='report',
            name='communityproject_manager',
            field=models.BooleanField(default=False, verbose_name=b'Community Manager vorhanden?'),
        ),
        migrations.AddField(
            model_name='report',
            name='cooperation_comments',
            field=models.TextField(blank=True, null=True, verbose_name=b'Allgemeine Kommentare zur Partnerschaft'),
        ),
        migrations.AddField(
            model_name='report',
            name='cooperation_ordering_experience',
            field=models.TextField(blank=True, help_text=b'Wie wird das Bestellen der Fahrr\xc3\xa4der und Ersatzteile empfunden?', null=True, verbose_name=b'Bestell Erlebnis'),
        ),
        migrations.AddField(
            model_name='report',
            name='cooperation_quality_bicycles',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='cooperation_quality_spares',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='cooperation_quality_tools',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='final_biggest_success',
            field=models.TextField(blank=True, null=True, verbose_name=b'Gr\xc3\xb6sste Erfolge dieses Jahres?'),
        ),
        migrations.AddField(
            model_name='report',
            name='final_future_challenges',
            field=models.TextField(blank=True, null=True, verbose_name=b'Gr\xc3\xb6sste Herausforderungen der Zukunft?'),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_event_attendance',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_event_organisation',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_flyer',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_mouth',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_other',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_poster',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_radio',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_socialmedia',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_channels_tv',
            field=models.CharField(blank=True, choices=[(b'1', b"We don't use it"), (b'2', b'rarely'), (b'3', b'occasionally'), (b'4', b'often'), (b'5', b'very often')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_customer_segments',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente'),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_customer_segments_other',
            field=models.CharField(blank=True, help_text=b"Bitte ausf\xc3\xbcllen, wenn bei der vorherigen Frage 'others' ausgew\xc3\xa4hlt wurde.", max_length=255, null=True, verbose_name=b'Andere'),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_customer_segments_top3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 3'),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='vocational_certificates',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Ausgestellte Zertifikate dieses Jahr'),
        ),
        migrations.AddField(
            model_name='report',
            name='vocational_certificates_ack',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Davon staatlich anerkannte Zertifikate'),
        ),
        migrations.AddField(
            model_name='report',
            name='vocational_exstudents_agriculture',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt in der Landwirtschaft arbeiten'),
        ),
        migrations.AddField(
            model_name='report',
            name='vocational_exstudents_bicycle_industry',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt im Velogewerbe arbeiten'),
        ),
        migrations.AddField(
            model_name='report',
            name='vocational_exstudents_energy',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt im Energie Sektor arbeiten'),
        ),
        migrations.AddField(
            model_name='report',
            name='vocational_exstudents_familiybusiness',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Ex-Studenten die jetzt im Familienbetrieb arbeiten'),
        ),
        migrations.AlterField(
            model_name='container',
            name='booked',
            field=models.BooleanField(default=False, verbose_name=b'Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='booked',
            field=models.BooleanField(default=False, verbose_name=b'Abgeschlossen'),
        ),
    ]
