# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0027_auto_20160720_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_areas',
            field=models.CharField(blank=True, choices=[(b'0', b'Schooling / Education'), (b'1', b'Entrepreneuership'), (b'2', b'Evnironment / Environmental protection'), (b'3', b'Mobility'), (b'4', b"Women's empowerment"), (b'5', b"Children's empowerment"), (b'6', b'Sports activities'), (b'7', b'Other')], max_length=1, null=True, verbose_name=b'Feld der Community Arbeit'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Anzahl Personen die vom Community Projekt profitiert haben'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_reinvest_profit_total',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'In Community Projekt re-investierter Betrag'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_ordering_experience',
            field=models.TextField(blank=True, help_text=b'Wie wird das Bestellen der Fahrr\xc3\xa4der und Ersatzteile empfunden?', null=True, verbose_name=b'Bestellerlebnis'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_quality_bicycles',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True, verbose_name=b'Qualit\xc3\xa4t der gelieferten Velos'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_quality_spares',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True, verbose_name=b'Qualit\xc3\xa4t der gelieferten Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='cooperation_quality_tools',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True, verbose_name=b'Qualit\xc3\xa4t der gelieferten Werkzeuge'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Andere'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Outlet'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Retail'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Shop'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Wholesale'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='mobilityprogram_people_benefitted',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Personen die vom Mobilit\xc3\xa4tsprogramm profitiert haben'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_program_duration',
            field=models.CharField(blank=True, choices=[(b'0', b'less than 3 months'), (b'1', b'6 - 12 months'), (b'2', b'12 - 18 months'), (b'3', b'18 - 24 months'), (b'4', b'more than 24 months')], max_length=1, null=True, verbose_name=b'Dauer des Besch\xc3\xa4ftigungsprogramms'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_areas',
            field=models.CharField(blank=True, choices=[(b'0', b'Schooling / Education'), (b'1', b'Entrepreneuership'), (b'2', b'Evnironment / Environmental protection'), (b'3', b'Mobility'), (b'4', b"Women's empowerment"), (b'5', b"Children's empowerment"), (b'6', b'Sports activities'), (b'7', b'Other')], max_length=1, null=True, verbose_name=b'Feld der Community Arbeit'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Anzahl Personen die vom Community Projekt profitiert haben'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_reinvest_profit_total',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'In Community Projekt re-investierter Betrag'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_ordering_experience',
            field=models.TextField(blank=True, help_text=b'Wie wird das Bestellen der Fahrr\xc3\xa4der und Ersatzteile empfunden?', null=True, verbose_name=b'Bestellerlebnis'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_quality_bicycles',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True, verbose_name=b'Qualit\xc3\xa4t der gelieferten Velos'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_quality_spares',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True, verbose_name=b'Qualit\xc3\xa4t der gelieferten Ersatzteile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cooperation_quality_tools',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2, null=True, verbose_name=b'Qualit\xc3\xa4t der gelieferten Werkzeuge'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Andere'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Outlet'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Retail'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Shop'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[(b'1', b'not good'), (b'2', b'ok'), (b'3', b'successful'), (b'4', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Wholesale'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mobilityprogram_people_benefitted',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anzahl Personen die vom Mobilit\xc3\xa4tsprogramm profitiert haben'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_program_duration',
            field=models.CharField(blank=True, choices=[(b'0', b'less than 3 months'), (b'1', b'6 - 12 months'), (b'2', b'12 - 18 months'), (b'3', b'18 - 24 months'), (b'4', b'more than 24 months')], max_length=1, null=True, verbose_name=b'Dauer des Besch\xc3\xa4ftigungsprogramms'),
        ),
    ]
