# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_auto_20160725_0904'),
        ('velafrica_sud', '0028_auto_20160722_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnersud',
            name='organisaton',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='partnersud',
            name='organisaton',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='organisation.Organisation'),
        ),
    ]
