# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0029_auto_20160725_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpartnersud',
            old_name='organisaton',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='partnersud',
            old_name='organisaton',
            new_name='organisation',
        ),
    ]
