# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0030_auto_20160725_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='area',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='contact',
            field=models.TextField(blank=True, help_text=b'WARNING: Will be removed soon', null=True, verbose_name=b'Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='description',
            field=models.TextField(blank=True, help_text=b'WARNING: Will be removed soon', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'WARNING: Will be removed soon', max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'WARNING: Will be removed soon', max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='name',
            field=models.CharField(help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Name der Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='street',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='website',
            field=models.URLField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Website'),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='zipcode',
            field=models.IntegerField(blank=True, help_text=b'WARNING: Will be removed soon', null=True),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='area',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='contact',
            field=models.TextField(blank=True, help_text=b'WARNING: Will be removed soon', null=True, verbose_name=b'Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='country',
            field=models.ForeignKey(help_text=b'WARNING: Will be removed soon', on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Country', verbose_name=b'Land'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='description',
            field=models.TextField(blank=True, help_text=b'WARNING: Will be removed soon', null=True),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'WARNING: Will be removed soon', max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'WARNING: Will be removed soon', max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='name',
            field=models.CharField(help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Name der Organisation'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='street',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='website',
            field=models.URLField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Website'),
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='zipcode',
            field=models.IntegerField(blank=True, help_text=b'WARNING: Will be removed soon', null=True),
        ),
    ]
