# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:24
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0031_auto_20160728_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersud',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnersud', to='organisation.Organisation'),
        ),
    ]
