# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 12:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0032_auto_20160728_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.BooleanField(default=True)),
                ('test2', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partnersud',
            options={'ordering': ['organisation__name'], 'verbose_name_plural': 'Partner S\xfcd'},
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='area',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='street',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='website',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='area',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='street',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='website',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='partnersud',
            name='organisation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partnersud', to='organisation.Organisation'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestChild',
            fields=[
                ('testparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='velafrica_sud.TestParent')),
                ('test3', models.BooleanField(default=False)),
            ],
            bases=('velafrica_sud.testparent',),
        ),
    ]
