# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0033_auto_20160729_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testchild',
            name='testparent_ptr',
        ),
        migrations.DeleteModel(
            name='TestChild',
        ),
        migrations.DeleteModel(
            name='TestParent',
        ),
    ]
