# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0034_auto_20160729_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='economic_import_taxes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Aktuelle Importz\xc3\xb6lle f\xc3\xbcr gebrauchte Fahrr\xc3\xa4der'),
        ),
        migrations.AlterField(
            model_name='report',
            name='economic_import_taxes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Aktuelle Importz\xc3\xb6lle f\xc3\xbcr gebrauchte Fahrr\xc3\xa4der'),
        ),
    ]
