# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:32
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0035_auto_20160802_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_customer_segments_top1',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 1'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='marketing_customer_segments_top2',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 2'),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_customer_segments_top1',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 1'),
        ),
        migrations.AddField(
            model_name='report',
            name='marketing_customer_segments_top2',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 2'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_customer_segments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_customer_segments_top3',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 3'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='mobilityprogram_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Anzahl Personen die vom Mobilit\xc3\xa4tsprogramm profitiert haben'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_customer_segments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_customer_segments_top3',
            field=models.CharField(blank=True, choices=[(b'men', b'Men'), (b'women', b'Women'), (b'children_students', b'Children/Students'), (b'teachers', b'Teachers'), (b'businessmen', b'Business Men'), (b'retail', b'Bicycle Retail Agents'), (b'wholesale', b'Bicycle Wholesale Agents'), (b'farmers', b'Farmers'), (b'safari', b'Safari companies'), (b'hospitals', b'Hospitals'), (b'other', b'other')], max_length=255, null=True, verbose_name=b'Kundensegmente Top 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mobilityprogram_people_benefitted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Anzahl Personen die vom Mobilit\xc3\xa4tsprogramm profitiert haben'),
        ),
    ]
