# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0036_auto_20160802_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='employment_notes',
            field=models.TextField(blank=True, null=True, verbose_name=b'Jobs Beschreibung'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employment_notes',
            field=models.TextField(blank=True, null=True, verbose_name=b'Jobs Beschreibung'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name=b'Name'),
        ),
    ]
