# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0037_auto_20160802_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
