# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0039_auto_20160809_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='communityproject_areas',
            field=models.CharField(blank=True, choices=[(b'education', b'Schooling / Education'), (b'entrepreneurship', b'Entrepreneuership'), (b'environment', b'Evnironment / Environmental protection'), (b'mobility', b'Mobility'), (b'women_empowerment', b"Women's empowerment"), (b'children_empowerment', b"Children's empowerment"), (b'sports_activist', b'Sports activities'), (b'other', b'Other')], max_length=1, null=True, verbose_name=b'Feld der Community Arbeit'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_event_attendance',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_event_organisation',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_flyer',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_mouth',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_other',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_poster',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_radio',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_socialmedia',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_channels_tv',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Andere'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Outlet'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Retail'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Shop'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Wholesale'),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='vocational_program_duration',
            field=models.CharField(blank=True, choices=[(b'less_than_3_months', b'less than 3 months'), (b'6_to_12_months', b'6 - 12 months'), (b'12_to_18_months', b'12 - 18 months'), (b'18_to_24_months', b'18 - 24 months'), (b'more_than_24_months', b'more than 24 months')], max_length=1, null=True, verbose_name=b'Dauer des Besch\xc3\xa4ftigungsprogramms'),
        ),
        migrations.AlterField(
            model_name='report',
            name='communityproject_areas',
            field=models.CharField(blank=True, choices=[(b'education', b'Schooling / Education'), (b'entrepreneurship', b'Entrepreneuership'), (b'environment', b'Evnironment / Environmental protection'), (b'mobility', b'Mobility'), (b'women_empowerment', b"Women's empowerment"), (b'children_empowerment', b"Children's empowerment"), (b'sports_activist', b'Sports activities'), (b'other', b'Other')], max_length=1, null=True, verbose_name=b'Feld der Community Arbeit'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_event_attendance',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_event_organisation',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_flyer',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_mouth',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_other',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_poster',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_radio',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_socialmedia',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_channels_tv',
            field=models.CharField(blank=True, choices=[(b'not_using_it', b"We don't use it"), (b'rarely', b'rarely'), (b'occasionally', b'occasionally'), (b'often', b'often'), (b'very often', b'very often')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_other',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Andere'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_outlets',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Outlet'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_retail',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Retail'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_shop',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Shop'),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_sales_wholesale',
            field=models.CharField(blank=True, choices=[(b'not_good', b'not good'), (b'ok', b'ok'), (b'successful', b'successful'), (b'not_using_it_yet', b'we do not use it (yet)')], max_length=1, null=True, verbose_name=b'Wholesale'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vocational_program_duration',
            field=models.CharField(blank=True, choices=[(b'less_than_3_months', b'less than 3 months'), (b'6_to_12_months', b'6 - 12 months'), (b'12_to_18_months', b'12 - 18 months'), (b'18_to_24_months', b'18 - 24 months'), (b'more_than_24_months', b'more than 24 months')], max_length=1, null=True, verbose_name=b'Dauer des Besch\xc3\xa4ftigungsprogramms'),
        ),
    ]
