# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0042_auto_20160815_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcontainer',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalforwarder',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnerstaff',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnersud',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalreportstaff',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalforwarder',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalpartnerstaff',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalpartnersud',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalreportstaff',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
    ]
