# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0043_auto_20170729_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='time_to_customer',
            field=models.IntegerField(blank=True, help_text=b'Anzahl Tage vom Verlad bis zur Ankunft im Zielhafen.', null=True, verbose_name=b'Versandzeit (Tage)'),
        ),
        migrations.AddField(
            model_name='historicalcontainer',
            name='time_to_customer',
            field=models.IntegerField(blank=True, help_text=b'Anzahl Tage vom Verlad bis zur Ankunft im Zielhafen.', null=True, verbose_name=b'Versandzeit (Tage)'),
        ),
    ]
