# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velafrica_sud', '0044_auto_20171010_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='time_to_customer',
            field=models.IntegerField(blank=True, help_text=b'Anzahl Tage vom Verlad bis zur Ankunft beim Partner.', null=True, verbose_name=b'Versandzeit (Tage)'),
        ),
        migrations.AlterField(
            model_name='historicalcontainer',
            name='time_to_customer',
            field=models.IntegerField(blank=True, help_text=b'Anzahl Tage vom Verlad bis zur Ankunft beim Partner.', null=True, verbose_name=b'Versandzeit (Tage)'),
        ),
    ]
