version: '2'
services:
  web:
    build: .
    entrypoint: /bin/bash
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
    tty: true
    stdin_open: true
    working_dir: /app-v/
    user: test
    volumes:
      - ./:/app-v/
      - ./pipenv:/home/test
  celery:
    build: .
    entrypoint: pipenv run celery worker -A velafrica.core.celery
    links:
      - postgres
      - redis
    tty: true
    stdin_open: true
    working_dir: /app-v/
    user: test
    volumes:
      - ./:/app-v/
      - ./pipenv:/home/test
  celery-beat:
    build: .
    entrypoint: pipenv run celery beat -A velafrica.core.celery
    links:
      - postgres
      - redis
    tty: true
    stdin_open: true
    working_dir: /app-v/
    user: test
    volumes:
      - ./:/app-v/
      - ./pipenv:/home/test

  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: foobar
      POSTGRES_USER: klub
      PGDATA: /var/lib/postgresql/data
