# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Aktiv')),
                ('description', models.TextField(verbose_name=b'Beschreibung')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Geldspendebetrag',
                'verbose_name_plural': 'Geldspendebetr\xe4ge',
            },
        ),
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Betrag')),
                ('empty_invoice', models.BooleanField(default=False, verbose_name=b'Leerer Einzahlungsschein')),
                ('number_invoices', models.IntegerField(default=1, verbose_name=b'Menge')),
                ('first_name', models.CharField(max_length=255, verbose_name=b'Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name=b'Nachname')),
                ('address', models.CharField(max_length=255, verbose_name=b'Adresse')),
                ('zip', models.CharField(max_length=255, verbose_name=b'PLZ, Ort')),
                ('comment', models.TextField(blank=True, verbose_name=b'Anmerkung')),
            ],
            options={
                'verbose_name': 'Einzahlungschein',
                'verbose_name_plural': 'Einzahlungsscheine',
            },
        ),
    ]
