# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkthroughRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name=b'Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name=b'Nachname')),
                ('phone', models.CharField(max_length=255, verbose_name=b'Telefonnummer')),
                ('email', models.CharField(max_length=255, verbose_name=b'E-Mail')),
                ('organizer_type', models.IntegerField(choices=[(1, b'Verein'), (2, b'Firma'), (3, b'Gemeinde'), (4, b'Kirchgemeinde'), (5, b'Schule'), (6, b'Liegenschaftsverwaltung'), (7, b'Privatperson'), (8, b'Andere')], default=1, verbose_name=b'Aufstellung')),
                ('organizer_type_note', models.TextField(blank=True, verbose_name=b'Bemerkung')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name=b'Datum von')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name=b'Datum bis')),
                ('pickup_time_start', models.CharField(blank=True, max_length=255, verbose_name=b'Annahmezeit von')),
                ('pickup_time_end', models.CharField(blank=True, max_length=255, verbose_name=b'Annahmezeit bis')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name=b'Adresse')),
                ('zip', models.CharField(blank=True, max_length=255, verbose_name=b'Postleitzahl')),
                ('address_note', models.TextField(blank=True, verbose_name=b'Standortbeschreibung')),
                ('expected_velos', models.IntegerField(choices=[(1, b'1 - 20'), (2, b'21 - 50'), (3, b'51 - 100'), (4, b'101 - 1000'), (5, b'> 1000')], default=1, verbose_name=b'Erwartete Menge gesammelter Velos')),
                ('can_store', models.BooleanField(default=False, verbose_name=b'Kann Velos vor Ort zwischenlagern')),
                ('can_deliver', models.BooleanField(default=False, verbose_name=b'Kann Abtransport zu Partner \xc3\xbcbernehmen')),
                ('velafrica_pickup', models.BooleanField(default=False, verbose_name=b'Abtransport durch Velafrica')),
                ('responsible_first_name', models.CharField(blank=True, max_length=255, verbose_name=b'Vorname')),
                ('responsible_last_name', models.CharField(blank=True, max_length=255, verbose_name=b'Nachname')),
                ('responsible_phone', models.CharField(blank=True, max_length=255, verbose_name=b'Telefonnummer')),
                ('responsible_email', models.CharField(blank=True, max_length=255, verbose_name=b'E-Mail')),
                ('supporter_count', models.IntegerField(choices=[(1, b'1 - 10'), (2, b'11 - 20'), (3, b'21 - 30'), (4, b'31 - 40'), (4, b'41 - 50')], default=1, verbose_name=b'Anzahl Helfer')),
                ('supporter_note', models.TextField(blank=True, verbose_name=b'Bemerkung')),
            ],
            options={
                'verbose_name': 'Sammelanlassanfrage',
                'verbose_name_plural': 'Sammelanlassanfragen',
            },
        ),
    ]
