# Generated by Django 2.1.12 on 2019-09-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_auto_20190902_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_event_address', to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_event_category', to='collection.EventCategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='sbbticketorder',
            name='dropoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Dropoff'),
        ),
    ]
