# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_auto_20161111_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkthroughrequest',
            name='organizer_type_note',
        ),
    ]
