# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0004_remove_walkthroughrequest_organizer_type_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkthroughrequest',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='walkthroughrequest',
            name='date_start',
        ),
        migrations.AddField(
            model_name='walkthroughrequest',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Datum'),
        ),
        migrations.AddField(
            model_name='walkthroughrequest',
            name='date_fixed',
            field=models.BooleanField(default=False, verbose_name=b'Datum fixiert'),
        ),
    ]
