# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_sbbticketorder'),
        ('public_site', '0005_auto_20161111_1437'),
    ]

    operations = [
    ]
