# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0007_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, verbose_name=b'Beschreibung'),
        ),
        migrations.AddField(
            model_name='content',
            name='path',
            field=models.CharField(default='index', max_length=255, verbose_name=b'Pfad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='key',
            field=models.CharField(max_length=255, verbose_name=b'Key'),
        ),
        migrations.AlterField(
            model_name='content',
            name='value',
            field=models.TextField(blank=True, verbose_name=b'Value'),
        ),
    ]
