# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0008_auto_20161116_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbbticketorder',
            name='amount',
            field=models.IntegerField(default=1, verbose_name=b'Anzahl'),
        ),
    ]
