# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0009_sbbticketorder_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('image', models.CharField(max_length=255, verbose_name=b'Bild-URL')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name=b'Position')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name=b'E-Mail')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name=b'Bild-URL')),
            ],
            options={
                'verbose_name': 'Teammitglied',
                'verbose_name_plural': 'Teammitglieder',
            },
        ),
    ]
