# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0010_award_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name=b'Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name=b'Nachname')),
                ('email', models.CharField(max_length=255, verbose_name=b'E-Mail')),
                ('note', models.TextField(verbose_name=b'Nachricht')),
            ],
            options={
                'verbose_name': 'Kontaktanfrage',
                'verbose_name_plural': 'Kontaktanfragen',
            },
        ),
    ]
