# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0011_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='text',
            field=models.TextField(default='', verbose_name=b'Text'),
            preserve_default=False,
        ),
    ]
