# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_squashed_0022_auto_20160809_2049'),
        ('public_site', '0013_auto_20161117_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('description', models.TextField(verbose_name=b'Beschreibung')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name=b'URL')),
                ('country', models.IntegerField(choices=[(1, b'Afrika'), (2, b'Schweiz')], verbose_name=b'Land')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.Address', verbose_name=b'Adresse')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partner',
            },
        ),
    ]
