# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0014_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, verbose_name=b'Beschreibung'),
        ),
    ]
