# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0017_auto_20161128_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name=b'Sortierung'),
        ),
    ]
