# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0022_auto_20161212_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('description', models.CharField(blank=True, help_text=b'Max. 140 Zeichen', max_length=140, verbose_name=b'Kurzbeschreibung')),
                ('link', models.URLField(verbose_name=b'URL')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name=b'Bild/Logo URL')),
                ('sorting', models.IntegerField(default=0, verbose_name=b'Sortierung')),
            ],
            options={
                'verbose_name': 'Unterst\xfctzer',
                'verbose_name_plural': 'Unterst\xfctzer',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
    ]
