# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0023_auto_20161213_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Aktiv'),
        ),
    ]
