# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0024_supporter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdatetime',
            name='time_end',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Bis'),
        ),
        migrations.AlterField(
            model_name='eventdatetime',
            name='time_start',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Von'),
        ),
    ]
