# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0025_auto_20161214_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Telefonnummer'),
        ),
    ]
