# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0026_teammember_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'E-Mail'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='note',
            field=models.TextField(blank=True, verbose_name=b'Nachricht'),
        ),
    ]
