# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0030_auto_20161228_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Kategorie/Bereich'),
        ),
    ]
