# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('sbbtracking', '0034_auto_20161004_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingStation',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TrackingStationQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name=b'Label')),
                ('query_order', models.IntegerField(default=0, verbose_name=b'Reihenfolge')),
                ('event_types', models.ManyToManyField(related_name='tracking_station_queries', to='sbbtracking.TrackingEventType')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='tracking_stations.TrackingStation')),
            ],
        ),
    ]
