# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0003_auto_20161012_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingstationquery',
            name='event_types',
        ),
    ]
