# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigPicture',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='big_picture_bigpicture', serialize=False, to='cms.CMSPlugin')),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('background_img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background', to='filer.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
