# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigpicture',
            name='min_height',
            field=models.IntegerField(default=500),
        ),
    ]
