# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 12:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import velafrica.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('velafrica_sud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbbtracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmailLog',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical email log',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTrackingEventType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('show_partner_info', models.BooleanField(default=False, help_text=b'Zeige Partnerinfo an wenn vorhanden (Wird aus hinterlegtem Container ausgelesen).')),
                ('description', models.TextField(blank=True, null=True)),
                ('email_text', models.TextField(blank=True, help_text=b'Text der im Benachrichtigugsemail den den Spender geschickt wird.', null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name=b'Symbolbild')),
                ('label', models.CharField(blank=True, help_text=b'Text Label auf der Tracking Seite (optional)', max_length=255, null=True, verbose_name=b'Label')),
                ('arrival_africa', models.BooleanField(default=False, help_text=b'Wird diese Option aktiviert, wird dieser Event Typ verwendet beim Container verbuchen um verlinkte Trackings zu markieren', verbose_name=b'Steht f\xc3\xbcr Ankunft in Afrika')),
                ('complete_tracking', models.BooleanField(default=False, help_text=b'Gilt ein Tracking mit diesem Event als beendet?', verbose_name=b'Schliesst Tracking ab?')),
                ('send_email', models.BooleanField(help_text=b'Aktivieren falls bei Erstellung eines Events dieser Art automatisch ein Email an den Spender versandt werden soll.')),
                ('latitude_default', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad Standard')),
                ('longitude_default', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad Standard')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical tracking event type',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVeloType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Bezeichnung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical velo type',
            },
        ),
        migrations.CreateModel(
            name='TrackingEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('show_partner_info', models.BooleanField(default=False, help_text=b'Zeige Partnerinfo an wenn vorhanden (Wird aus hinterlegtem Container ausgelesen).')),
                ('description', models.TextField(blank=True, null=True)),
                ('email_text', models.TextField(blank=True, help_text=b'Text der im Benachrichtigugsemail den den Spender geschickt wird.', null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, null=True, storage=velafrica.core.storage.MyStorage(), upload_to=b'tracking/eventtypes/', verbose_name=b'Symbolbild')),
                ('label', models.CharField(blank=True, help_text=b'Text Label auf der Tracking Seite (optional)', max_length=255, null=True, verbose_name=b'Label')),
                ('arrival_africa', models.BooleanField(default=False, help_text=b'Wird diese Option aktiviert, wird dieser Event Typ verwendet beim Container verbuchen um verlinkte Trackings zu markieren', verbose_name=b'Steht f\xc3\xbcr Ankunft in Afrika')),
                ('complete_tracking', models.BooleanField(default=False, help_text=b'Gilt ein Tracking mit diesem Event als beendet?', verbose_name=b'Schliesst Tracking ab?')),
                ('send_email', models.BooleanField(help_text=b'Aktivieren falls bei Erstellung eines Events dieser Art automatisch ein Email an den Spender versandt werden soll.')),
                ('latitude_default', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad Standard')),
                ('longitude_default', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad Standard')),
                ('required_previous_event', models.ForeignKey(blank=True, help_text=b'Wird dieses Feld ausgef\xc3\xbcllt, muss der letzte Event auf dem Tracking vom angegebenen Typ sein, sonst kann kein Event dieses Event Typs hinzugef\xc3\xbcgt werden. Dies soll verhindern dass Events vergessen gehen.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.TrackingEventType', verbose_name=b'Vorangehender Event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VeloType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Bezeichnung')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicaltrackingeventstate',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-tracking_no']},
        ),
        migrations.RemoveField(
            model_name='historicaltracking',
            name='number_of_velos',
        ),
        migrations.RemoveField(
            model_name='historicaltracking',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='historicaltracking',
            name='street',
        ),
        migrations.RemoveField(
            model_name='historicaltracking',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='historicaltracking',
            name='town',
        ),
        migrations.RemoveField(
            model_name='historicaltracking',
            name='trackingno',
        ),
        migrations.RemoveField(
            model_name='historicaltrackingevent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='number_of_velos',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='street',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='town',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='trackingno',
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='complete',
            field=models.BooleanField(default=False, verbose_name=b'Abgeschlossen'),
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='container',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='velafrica_sud.Container'),
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='last_event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEvent'),
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Bemerkung'),
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='tracking_no',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name=b'Tracking Nummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='vpn',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='complete',
            field=models.BooleanField(default=False, verbose_name=b'Abgeschlossen'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Container'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='tracking_last_event', to='sbbtracking.TrackingEvent', verbose_name=b'Letzter Event'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Bemerkung'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='tracking_no',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name=b'Tracking Nummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='vpn',
            field=models.ForeignKey(blank=True, help_text=b'wird momentan noch nicht ber\xc3\xbccksichtigt', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Partner'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text=b'Organisation welche den Event erstellt hat.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Organisation'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator], verbose_name=b'Email'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vorname'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Nachname'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Zeitpunkt'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='note',
            field=models.CharField(blank=True, help_text=b'interne Bemerkung, nirgends ersichtlich f\xc3\xbcr Spender (optional)', max_length=255, null=True, verbose_name=b'Bemerkung'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator], verbose_name=b'Email'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vorname'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Nachname'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Zeitpunkt'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='note',
            field=models.CharField(blank=True, help_text=b'interne Bemerkung, nirgends ersichtlich f\xc3\xbcr Spender (optional)', max_length=255, null=True, verbose_name=b'Bemerkung'),
        ),
        migrations.DeleteModel(
            name='HistoricalTrackingEventState',
        ),
        migrations.AddField(
            model_name='historicaltrackingeventtype',
            name='required_previous_event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEventType'),
        ),
        migrations.AddField(
            model_name='historicalemaillog',
            name='tracking',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.Tracking'),
        ),
        migrations.AddField(
            model_name='historicalemaillog',
            name='tracking_event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEvent'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.Tracking'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='tracking_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.TrackingEvent'),
        ),
        migrations.AddField(
            model_name='historicaltracking',
            name='velo_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.VeloType'),
        ),
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='event_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEventType'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='velo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.VeloType'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='event_type',
            field=models.ForeignKey(default=1, help_text=b'Art des Events', on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.TrackingEventType'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='trackingevent',
            name='state',
        ),
        migrations.AlterUniqueTogether(
            name='trackingevent',
            unique_together=set([('event_type', 'tracking')]),
        ),
        migrations.DeleteModel(
            name='TrackingEventState',
        ),
    ]
