# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import velafrica.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0002_auto_20181019_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalemaillog',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='last_event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEvent', verbose_name='Letzter Event'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='tracking_no',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Tracking Nummer'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='vpn',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='wird momentan noch nicht berücksichtigt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zeitpunkt'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='event_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Art des Events', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEventType'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='note',
            field=models.CharField(blank=True, help_text='interne Bemerkung, nirgends ersichtlich für Spender (optional)', max_length=255, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organisation welche den Event erstellt hat.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='arrival_africa',
            field=models.BooleanField(default=False, help_text='Wird diese Option aktiviert, wird dieser Event Typ verwendet beim Container verbuchen um verlinkte Trackings zu markieren', verbose_name='Steht für Ankunft in Afrika'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='complete_tracking',
            field=models.BooleanField(default=False, help_text='Gilt ein Tracking mit diesem Event als beendet?', verbose_name='Schliesst Tracking ab?'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='email_text',
            field=models.TextField(blank=True, help_text='Text der im Benachrichtigugsemail den den Spender geschickt wird.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Symbolbild'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='label',
            field=models.CharField(blank=True, help_text='Text Label auf der Tracking Seite (optional)', max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='latitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad Standard'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='longitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad Standard'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='required_previous_event',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Wird dieses Feld ausgefüllt, muss der letzte Event auf dem Tracking vom angegebenen Typ sein, sonst kann kein Event dieses Event Typs hinzugefügt werden. Dies soll verhindern dass Events vergessen gehen.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEventType', verbose_name='Vorangehender Event'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='send_email',
            field=models.BooleanField(help_text='Aktivieren falls bei Erstellung eines Events dieser Art automatisch ein Email an den Spender versandt werden soll.'),
        ),
        migrations.AlterField(
            model_name='historicaltrackingeventtype',
            name='show_partner_info',
            field=models.BooleanField(default=False, help_text='Zeige Partnerinfo an wenn vorhanden (Wird aus hinterlegtem Container ausgelesen).'),
        ),
        migrations.AlterField(
            model_name='historicalvelotype',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalvelotype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='tracking_last_event', to='sbbtracking.TrackingEvent', verbose_name='Letzter Event'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tracking Nummer'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='vpn',
            field=models.ForeignKey(blank=True, help_text='wird momentan noch nicht berücksichtigt', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zeitpunkt'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='event_type',
            field=models.ForeignKey(help_text='Art des Events', on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.TrackingEventType'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='note',
            field=models.CharField(blank=True, help_text='interne Bemerkung, nirgends ersichtlich für Spender (optional)', max_length=255, null=True, verbose_name='Bemerkung'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation welche den Event erstellt hat.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='arrival_africa',
            field=models.BooleanField(default=False, help_text='Wird diese Option aktiviert, wird dieser Event Typ verwendet beim Container verbuchen um verlinkte Trackings zu markieren', verbose_name='Steht für Ankunft in Afrika'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='complete_tracking',
            field=models.BooleanField(default=False, help_text='Gilt ein Tracking mit diesem Event als beendet?', verbose_name='Schliesst Tracking ab?'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='email_text',
            field=models.TextField(blank=True, help_text='Text der im Benachrichtigugsemail den den Spender geschickt wird.', null=True),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[600, 600], storage=velafrica.core.storage.MyStorage(), upload_to='tracking/eventtypes/', verbose_name='Symbolbild'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='label',
            field=models.CharField(blank=True, help_text='Text Label auf der Tracking Seite (optional)', max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='latitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad Standard'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='longitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad Standard'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='required_previous_event',
            field=models.ForeignKey(blank=True, help_text='Wird dieses Feld ausgefüllt, muss der letzte Event auf dem Tracking vom angegebenen Typ sein, sonst kann kein Event dieses Event Typs hinzugefügt werden. Dies soll verhindern dass Events vergessen gehen.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.TrackingEventType', verbose_name='Vorangehender Event'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='send_email',
            field=models.BooleanField(help_text='Aktivieren falls bei Erstellung eines Events dieser Art automatisch ein Email an den Spender versandt werden soll.'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='show_partner_info',
            field=models.BooleanField(default=False, help_text='Zeige Partnerinfo an wenn vorhanden (Wird aus hinterlegtem Container ausgelesen).'),
        ),
        migrations.AlterField(
            model_name='velotype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Bezeichnung'),
        ),
    ]
