# Generated by Django 2.1.12 on 2019-09-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0003_auto_20190326_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='velafrica_sud.Container'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_last_event', to='sbbtracking.TrackingEvent', verbose_name='Letzter Event'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='velo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbbtracking.VeloType'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.Tracking'),
        ),
        migrations.AlterField(
            model_name='trackingeventtype',
            name='required_previous_event',
            field=models.ForeignKey(blank=True, help_text='Wird dieses Feld ausgefüllt, muss der letzte Event auf dem Tracking vom angegebenen Typ sein, sonst kann kein Event dieses Event Typs hinzugefügt werden. Dies soll verhindern dass Events vergessen gehen.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbbtracking.TrackingEventType', verbose_name='Vorangehender Event'),
        ),
    ]
