# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0022_auto_20160510_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltracking',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Letztes Update'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Letztes Update'),
        ),
    ]
