# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0023_auto_20160601_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltracking',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='last_update',
        ),
    ]
