# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0024_auto_20160601_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalemaillog',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaltrackingevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Zeitpunkt'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Zeitpunkt'),
        ),
    ]
