# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0026_auto_20160609_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrackingeventtype',
            name='required_previous_event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sbbtracking.TrackingEventType'),
        ),
        migrations.AddField(
            model_name='trackingeventtype',
            name='required_previous_event',
            field=models.ForeignKey(blank=True, help_text=b'Wird dieses Feld ausgef\xc3\xbcllt, muss der letzte Event auf dem Tracking vom angegebenen Typ sein, sonst kann kein Event dieses Event Typs hinzugef\xc3\xbcgt werden. Dies soll verhindern dass Events vergessen gehen.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sbbtracking.TrackingEventType', verbose_name=b'Vorangehender Event'),
        ),
    ]
