# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0027_auto_20160614_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrackingeventtype',
            name='arrival_africa',
            field=models.BooleanField(default=False, help_text=b'Wird diese Option aktiviert, wird dieser Event Typ verwendet beim Container verbuchen um verlinkte Trackings zu markieren', verbose_name=b'Steht f\xc3\xbcr Ankunft in Afrika'),
        ),
        migrations.AddField(
            model_name='trackingeventtype',
            name='arrival_africa',
            field=models.BooleanField(default=False, help_text=b'Wird diese Option aktiviert, wird dieser Event Typ verwendet beim Container verbuchen um verlinkte Trackings zu markieren', verbose_name=b'Steht f\xc3\xbcr Ankunft in Afrika'),
        ),
    ]
