# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models

import velafrica.sbbtracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0028_auto_20160620_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(velafrica.sbbtracking.models.get_last_event), related_name='tracking_last_event', to='sbbtracking.TrackingEvent', verbose_name=b'Letzter Event'),
        ),
    ]
