# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0030_auto_20160620_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltracking',
            name='complete',
            field=models.BooleanField(default=False, verbose_name=b'Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='complete',
            field=models.BooleanField(default=False, verbose_name=b'Abgeschlossen'),
        ),
    ]
