# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0032_auto_20160727_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
        migrations.AddField(
            model_name='historicaltrackingeventtype',
            name='latitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad Standard'),
        ),
        migrations.AddField(
            model_name='historicaltrackingeventtype',
            name='longitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad Standard'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad'),
        ),
        migrations.AddField(
            model_name='trackingeventtype',
            name='latitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad Standard'),
        ),
        migrations.AddField(
            model_name='trackingeventtype',
            name='longitude_default',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad Standard'),
        ),
    ]
