# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0022_auto_20160809_2049'),
        ('sbbtracking', '0033_auto_20160808_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrackingevent',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text=b'Organisation welche den Event erstellt hat.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Organisation'),
        ),
    ]
