# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0035_auto_20170729_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltracking',
            name='tracking_no',
            field=models.CharField(db_index=True, max_length=50, verbose_name=b'Tracking Nummer'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_no',
            field=models.CharField(max_length=50, unique=True, verbose_name=b'Tracking Nummer'),
        ),
    ]
