# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import velafrica.bikes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('velafrica_sud', '0002_auto_20190326_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('', '-'), ('MTB', 'MTB'), ('TW', 'Touring Woman'), ('TM', 'Touring Man'), ('K', 'Kids'), ('C', 'Classic'), ('R', 'Racing')], max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('visum', models.CharField(blank=True, max_length=255)),
                ('a_plus', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('gearing', models.CharField(blank=True, default='', max_length=255)),
                ('drivetrain', models.CharField(blank=True, default='', max_length=255)),
                ('type_of_brake', models.CharField(blank=True, choices=[('', '-'), ('hd', 'hydraulic disc'), ('rb', 'rim brake'), ('hrb', 'rim brake')], default='', max_length=255)),
                ('brake', models.CharField(blank=True, default='', max_length=255)),
                ('colour', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.CharField(blank=True, choices=[('', '-'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='', max_length=255)),
                ('suspension', models.CharField(blank=True, max_length=255, null=True)),
                ('extraordinary', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to=velafrica.bikes.models.bike_images)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_modified', models.DateField(auto_now=True, null=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='velafrica_sud.Container')),
            ],
        ),
    ]
