# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import velafrica.bikes.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190827_1322'),
        ('bikes', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='bike',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Warehouse', verbose_name='Lager'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='a_plus',
            field=models.BooleanField(default=False, verbose_name='A+'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brake',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Marke der Bremsen'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Marke'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='velafrica_sud.Container', verbose_name='Container'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='drivetrain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Gänge'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='extraordinary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spezielles'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='gearing',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Schaltung'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=velafrica.bikes.models.bike_images, verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='number',
            field=models.IntegerField(default=velafrica.bikes.models.next_a_plus_number, unique=True, verbose_name='Nr.'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='size',
            field=models.CharField(blank=True, choices=[('', '-'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='', max_length=255, verbose_name='Grösse'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='suspension',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Federung'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(choices=[('', '-'), ('MTB', 'MTB'), ('TW', 'Touring Woman'), ('TM', 'Touring Man'), ('K', 'Kids'), ('C', 'Classic'), ('R', 'Racing')], max_length=255, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='type_of_brake',
            field=models.CharField(blank=True, choices=[('', '-'), ('hd', 'hydraulic disc'), ('rb', 'rim brake'), ('hrb', 'rim brake')], default='', max_length=255, verbose_name='Bremsentyp'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='visum',
            field=models.CharField(blank=True, max_length=255, verbose_name='Visum'),
        ),
        migrations.AddField(
            model_name='bike',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
