# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20190904_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='type_of_brake',
        ),
    ]
