# Generated by Django 2.1.12 on 2019-09-25 17:56

from django.db import migrations
import django_resized.forms
import velafrica.bikes.models
import velafrica.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_remove_bike_type_of_brake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[1920, 1080], storage=velafrica.core.storage.MyStorage(), upload_to=velafrica.bikes.models.bike_images, verbose_name='Image'),
        ),
    ]
