# Generated by Django 2.1.12 on 2019-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_auto_20190925_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='status',
            field=models.IntegerField(choices=[{0, 'Normal'}, {1, 'Dismissed'}], default=0, verbose_name='status'),
        ),
    ]
