# Generated by Django 2.1.12 on 2020-01-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bikes', '0007_bike_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'bike categories',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.BikeCategory', verbose_name='Type'),
        ),
    ]
