# Generated by Django 2.1.15 on 2020-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_bike_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['-number']},
        ),
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Dismissed')], default=0, help_text='Dismissed = bike is neither in stock nor sold.', verbose_name='status'),
        ),
    ]
