# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import velafrica.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='articlenr_start',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Kategorienummer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Colour code to use for this category (hex value, i.e. #000 or #000000)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_hexcode', message='Must be a hexcode (e.g. #000 or #000000)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Product picture.', keep_meta=True, null=True, quality=75, size=[500, 500], storage=velafrica.core.storage.MyStorage(), upload_to='stock/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kategoriebezeichnung'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='articlenr_start',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='Kategorienummer'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='color',
            field=models.CharField(blank=True, help_text='Colour code to use for this category (hex value, i.e. #000 or #000000)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_hexcode', message='Must be a hexcode (e.g. #000 or #000000)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='image',
            field=models.TextField(blank=True, help_text='Product picture.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kategoriebezeichnung'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='articlenr',
            field=models.CharField(db_index=True, help_text='Die Velafrica Artikelnummer (in der Form 123.123)', max_length=7, verbose_name='Artikelnummer'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Die Hauptkategorie des Produktes.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Hinweise zur Qualität bzw Hinweise und Ergänzung', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='hscode',
            field=models.CharField(max_length=7, verbose_name='Harmonized System Code'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Produktbild'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Produktbezeichnung'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Produktbezeichnung EN'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Produktbezeichnung FR'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='packaging_unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Verpackungseinheit (VE)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Verkaufspreis'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='amount',
            field=models.IntegerField(default=0, help_text='Anzahl der Produkte an Lager', verbose_name='Stückzahl'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, help_text='Tag und Zeit wann das Objekt zuletzt geändert wurde.'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Das Lager wo sich der Stock befindet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse', verbose_name='Lager'),
        ),
        migrations.AlterField(
            model_name='historicalstocklist',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstocklistposition',
            name='amount',
            field=models.IntegerField(verbose_name='Stückzahl'),
        ),
        migrations.AlterField(
            model_name='historicalstocklistposition',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstocklistposition',
            name='stocklist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.StockList', verbose_name='StockList'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='booked',
            field=models.BooleanField(default=False, help_text='Gibt an ob der Stock bereits angepasst wurde.'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ausführdatum'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='stocklist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.StockList', verbose_name='Stock List'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse', verbose_name='Herkunfts-Lager'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='warehouse_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Warehouse', verbose_name='Ziel-Lager'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Nur angeben wenn die Lageradresse von Organisationsadresse abweicht.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Address', verbose_name='Andere Adresse als Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='description',
            field=models.CharField(blank=True, help_text='Beschreibung / Bemerkungen zum Lager', max_length=255, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Bild des Lagers'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='name',
            field=models.CharField(help_text='Der Name / Bezeichnung des Lagers', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='notify_on_incoming_transport',
            field=models.TextField(blank=True, help_text='Eine Emailadressen pro Zeile. Hier eingetragene Emailadressen werden jedesmal benachrichtigt, sobald eine neue Fahrt  mit Ersatzteilen zu diesem Lager erfasst wird.', null=True, verbose_name='Über angeliferte Ersatzteile informieren'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Die Organisation zu welcher das Lager gehört. (Nur VPN Schweiz Partner)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='stock_management',
            field=models.BooleanField(default=False, help_text='Gibt an ob automatisches Stock-Management aktiviert ist, d.h. ob bei Stock Verschiebungen der Stock automatisch angepasst werden soll.', verbose_name='Automatisches Stock-Management'),
        ),
        migrations.AlterField(
            model_name='product',
            name='articlenr',
            field=models.CharField(help_text='Die Velafrica Artikelnummer (in der Form 123.123)', max_length=7, unique=True, verbose_name='Artikelnummer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Die Hauptkategorie des Produktes.', on_delete=django.db.models.deletion.CASCADE, to='stock.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Hinweise zur Qualität bzw Hinweise und Ergänzung', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hscode',
            field=models.CharField(max_length=7, verbose_name='Harmonized System Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[500, 500], storage=velafrica.core.storage.MyStorage(), upload_to='stock/products/', verbose_name='Produktbild'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Produktbezeichnung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Produktbezeichnung EN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Produktbezeichnung FR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Verpackungseinheit (VE)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Verkaufspreis'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0, help_text='Anzahl der Produkte an Lager', verbose_name='Stückzahl'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Tag und Zeit wann das Objekt zuletzt geändert wurde.'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(help_text='Das Lager wo sich der Stock befindet', on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse', verbose_name='Lager'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='booked',
            field=models.BooleanField(default=False, help_text='Indicates if stock adjustments have been made.'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='stock_change_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=255),
        ),
        migrations.AlterField(
            model_name='stockchangelistpos',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Stückzahl'),
        ),
        migrations.AlterField(
            model_name='stocklistposition',
            name='amount',
            field=models.IntegerField(verbose_name='Stückzahl'),
        ),
        migrations.AlterField(
            model_name='stocklistposition',
            name='stocklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockList', verbose_name='StockList'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='booked',
            field=models.BooleanField(default=False, help_text='Gibt an ob der Stock bereits angepasst wurde.'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ausführdatum'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='stocklist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.StockList', verbose_name='Stock List'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='warehouse_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_from', to='stock.Warehouse', verbose_name='Herkunfts-Lager'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='warehouse_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_to', to='stock.Warehouse', verbose_name='Ziel-Lager'),
        ),
        migrations.AlterField(
            model_name='stocktransferlistpos',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Stückzahl'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Nur angeben wenn die Lageradresse von Organisationsadresse abweicht.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name='Andere Adresse als Organisation'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(blank=True, help_text='Beschreibung / Bemerkungen zum Lager', max_length=255, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[500, 500], storage=velafrica.core.storage.MyStorage(), upload_to='stock/warehouses/', verbose_name='Bild des Lagers'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text='Der Name / Bezeichnung des Lagers', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='notify_on_incoming_transport',
            field=models.TextField(blank=True, help_text='Eine Emailadressen pro Zeile. Hier eingetragene Emailadressen werden jedesmal benachrichtigt, sobald eine neue Fahrt  mit Ersatzteilen zu diesem Lager erfasst wird.', null=True, verbose_name='Über angeliferte Ersatzteile informieren'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='organisation',
            field=models.ForeignKey(help_text='Die Organisation zu welcher das Lager gehört. (Nur VPN Schweiz Partner)', on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='stock_management',
            field=models.BooleanField(default=False, help_text='Gibt an ob automatisches Stock-Management aktiviert ist, d.h. ob bei Stock Verschiebungen der Stock automatisch angepasst werden soll.', verbose_name='Automatisches Stock-Management'),
        ),
    ]
