# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190326_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='stock_change_type',
            field=models.CharField(choices=[('out', 'out'), ('in', 'in')], max_length=255),
        ),
    ]
