# Generated by Django 2.1.15 on 2020-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200324_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='stock_change_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=255),
        ),
    ]
