# Generated by Django 2.1.15 on 2020-05-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200527_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='stock_change_type',
            field=models.CharField(choices=[('out', 'out'), ('in', 'in')], max_length=255),
        ),
    ]
