# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20160509_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstocklist',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Ausf\xc3\xbchrdatum'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Ausf\xc3\xbchrdatum'),
        ),
    ]
