# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20160608_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstocklist',
            name='stocktransfer',
        ),
        migrations.RemoveField(
            model_name='stocklist',
            name='stocktransfer',
        ),
        migrations.AddField(
            model_name='historicalstocktransfer',
            name='stocklist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.StockList'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='stocklist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.StockList', verbose_name=b'Stock List'),
            preserve_default=False,
        ),
    ]
