# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20160608_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['warehouse', 'product'], 'permissions': (('stock_is_admin', 'Can see and edit all stocks from every warehouse.'),)},
        ),
    ]
