# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20160615_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['warehouse', 'product'], 'permissions': (('is_admin', 'Stock Admin - Can edit all stocks from every warehouse.'),)},
        ),
    ]
