# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20160615_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwarehouse',
            name='notify_on_incoming_transport_email',
            field=models.TextField(blank=True, help_text=b'Eine Emailadressen pro Zeile. Hier eingetragene Emailadressen werden jedesmal benachrichtigt, sobald eine neue Fahrt  mit Ersatzteilen zu diesem Lager erfasst wird.', null=True, verbose_name=b'\xc3\x9cber angeliferte Ersatzteile informieren'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='notify_on_incoming_transport_email',
            field=models.TextField(blank=True, help_text=b'Eine Emailadressen pro Zeile. Hier eingetragene Emailadressen werden jedesmal benachrichtigt, sobald eine neue Fahrt  mit Ersatzteilen zu diesem Lager erfasst wird.', null=True, verbose_name=b'\xc3\x9cber angeliferte Ersatzteile informieren'),
        ),
    ]
