# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20160621_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwarehouse',
            old_name='notify_on_incoming_transport_email',
            new_name='notify_on_incoming_transport',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='notify_on_incoming_transport_email',
            new_name='notify_on_incoming_transport',
        ),
    ]
