# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20160611_0950'),
        ('stock', '0016_auto_20160621_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwarehouse',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Latitude (Breitengrad)'),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Longitude (L\xc3\xa4ngengrad)'),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='municipality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Municipality'),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strasse'),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='street_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strassennummer'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Latitude (Breitengrad)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Longitude (L\xc3\xa4ngengrad)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Municipality'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strasse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='street_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strassennummer'),
        ),
    ]
