# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20160629_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwarehouse',
            name='street_no',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='street_no',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Municipality', verbose_name=b'Ort'),
        ),
    ]
