# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import velafrica.core.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0014_auto_20160722_1712'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0018_auto_20160708_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Kommentare')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('from_org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical invoice',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPartnerSud',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(blank=True, help_text=b'Foto vom Partner vor Ort.', max_length=100, null=True)),
                ('org_form', models.CharField(blank=True, max_length=255, null=True)),
                ('legalform', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Organisationsform')),
                ('partner_since', models.IntegerField(blank=True, help_text=b'Jahr', null=True, verbose_name=b'Partner seit...')),
                ('vocational_training', models.BooleanField(default=False, verbose_name=b'Bietet Berufsbildung an')),
                ('infrastructure', models.TextField(blank=True, help_text=b'\xc3\x9cbersicht \xc3\xbcber die Infrastruktur vor Ort (Anzahl Arbeitspl\xc3\xa4tze, Lagerm\xc3\xb6glichkeiten, Art der Geb\xc3\xa4ude etc)', null=True, verbose_name=b'Infrastruktur')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical partner sud',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=b'St\xc3\xbcckzahl')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Kommentare')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.Product')),
                ('to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical purchase order',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalesOrder',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Kommentare')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical sales order',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Kommentare')),
                ('from_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_from', to='organisation.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceListPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=b'St\xc3\xbcckzahl')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerSud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, help_text=b'Foto vom Partner vor Ort.', null=True, storage=velafrica.core.ftp.MyFTPStorage(), upload_to=b'velafrica_sud/partner/')),
                ('org_form', models.CharField(blank=True, max_length=255, null=True)),
                ('legalform', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Organisationsform')),
                ('partner_since', models.IntegerField(blank=True, help_text=b'Jahr', null=True, verbose_name=b'Partner seit...')),
                ('vocational_training', models.BooleanField(default=False, verbose_name=b'Bietet Berufsbildung an')),
                ('infrastructure', models.TextField(blank=True, help_text=b'\xc3\x9cbersicht \xc3\xbcber die Infrastruktur vor Ort (Anzahl Arbeitspl\xc3\xa4tze, Lagerm\xc3\xb6glichkeiten, Art der Geb\xc3\xa4ude etc)', null=True, verbose_name=b'Infrastruktur')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation')),
            ],
            options={
                'ordering': ['organisation__name'],
                'verbose_name_plural': 'Partner S\xfcd',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=b'St\xc3\xbcckzahl')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Kommentare')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderListPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=b'St\xc3\xbcckzahl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
                ('purchaseorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Kommentare')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderListPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=b'St\xc3\xbcckzahl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.SalesOrder')),
            ],
        ),
        migrations.CreateModel(
            name='StockChangeListPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=b'St\xc3\xbcckzahl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferListPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=b'St\xc3\xbcckzahl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
                ('stocktransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockTransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockchange',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockchangelistpos',
            name='stockchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockChange'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchaseorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='salesorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.SalesOrder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_to', to='organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='purchaseorder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='salesorder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.SalesOrder'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='to_org',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderlistpos',
            unique_together=set([('salesorder', 'product')]),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderlistpos',
            unique_together=set([('purchaseorder', 'product')]),
        ),
    ]
