# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20160725_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpartnersud',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='partnersud',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='HistoricalPartnerSud',
        ),
        migrations.DeleteModel(
            name='PartnerSud',
        ),
    ]
