# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20160725_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='state',
            field=models.CharField(choices=[(b'3', b'invoiced'), (b'2', b'shipped'), (b'1', b'confirmed'), (b'0', b'draft')], default=b'0', max_length=2, verbose_name=b'Status'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='state',
            field=models.CharField(choices=[(b'3', b'invoiced'), (b'2', b'shipped'), (b'1', b'confirmed'), (b'0', b'draft')], default=b'0', max_length=2, verbose_name=b'Status'),
        ),
    ]
