# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_auto_20160727_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Einkaufspreis'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Einkaufspreis'),
        ),
    ]
