# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_auto_20160727_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Verkaufspreis'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Einkaufspreis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Verkaufspreis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Einkaufspreis'),
        ),
    ]
