# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_auto_20160728_1847'),
        ('stock', '0028_auto_20160727_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwarehouse',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='historicalwarehouse',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='historicalwarehouse',
            name='street',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='street',
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Address'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.ForeignKey(blank=True, help_text=b'Nur angeben wenn die Lageradresse von Organisationsadresse abweicht.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name=b'Andere Adresse als Organisation'),
        ),
    ]
