# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_auto_20160728_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Einkaufspreis'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Verkaufspreis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Einkaufspreis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=b'Verkaufspreis'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='organisation',
            field=models.ForeignKey(help_text=b'Die Organisation zu welcher das Lager geh\xc3\xb6rt. (Nur VPN Schweiz Partner)', on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Organisation'),
        ),
    ]
