# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_auto_20160803_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='booked',
            field=models.BooleanField(default=False, help_text=b'Indicates if stock adjustments have been made.'),
        ),
    ]
