# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_auto_20160810_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstocklist',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Stock Liste'},
        ),
        migrations.AlterModelOptions(
            name='historicalstocklistposition',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Stock List Position'},
        ),
        migrations.AlterModelOptions(
            name='historicalstocktransfer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Stock Transfer'},
        ),
        migrations.AlterModelOptions(
            name='stockchange',
            options={'verbose_name': 'Stock Change', 'verbose_name_plural': 'Stock Changes'},
        ),
        migrations.AlterModelOptions(
            name='stockchangelistpos',
            options={'verbose_name': 'Stock Change List Position', 'verbose_name_plural': 'Stock Change List Positions'},
        ),
        migrations.AlterModelOptions(
            name='stocklist',
            options={'verbose_name': 'Stock Liste', 'verbose_name_plural': 'Stock Listen'},
        ),
        migrations.AlterModelOptions(
            name='stocklistposition',
            options={'verbose_name': 'Stock List Position', 'verbose_name_plural': 'Stock List Positionen'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-date'], 'verbose_name': 'Stock Transfer', 'verbose_name_plural': 'Stock Transfers'},
        ),
        migrations.AlterModelOptions(
            name='stocktransferlistpos',
            options={'verbose_name': 'Stock Transfer List Position', 'verbose_name_plural': 'Stock Transfers List Positionen'},
        ),
    ]
