# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_auto_20160811_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcategory',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstocklist',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstocklistposition',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstocktransfer',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstocklist',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstocklistposition',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
    ]
