# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='from_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_from', to='organisation.Organisation', verbose_name=b'Anbieter'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='to_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_to', to='organisation.Organisation', verbose_name=b'Kunde'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='from_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_from', to='organisation.Organisation', verbose_name=b'Anbieter'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='to_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_to', to='organisation.Organisation', verbose_name=b'Kunde'),
        ),
    ]
