# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_auto_20160727_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchaseorder',
            field=models.ForeignKey(blank=True, help_text=b'Wird hier ein Kaufauftrag (Purchase Order) hinterlegt, wird f\xc3\xbcr die Berechnung des Rechnungsbetrags der Einkaufspreis verwendet.', null=True, on_delete=django.db.models.deletion.CASCADE, to='commission.PurchaseOrder', verbose_name=b'Kaufauftrag (Purchase Order)'),
        ),
    ]
