# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbbtracking', '0034_auto_20161004_2150'),
        ('tracking_stations', '0006_trackingstationquery_plugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingstationquery',
            name='event_types',
        ),
        migrations.AddField(
            model_name='trackingstationquery',
            name='event_types',
            field=models.ManyToManyField(to='sbbtracking.TrackingEventType'),
        ),
    ]
