# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_stations', '0008_auto_20161013_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingstationquery',
            name='event_types',
            field=models.ManyToManyField(related_name='tracking_station_queries', to='sbbtracking.TrackingEventType'),
        ),
    ]
