# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('counter', '0002_auto_20160129_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name=b'Visum Werkstattchef'),
        ),
        migrations.AddField(
            model_name='entry',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Verarbeitsungsort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalentry',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name=b'Visum Werkstattchef'),
        ),
        migrations.AddField(
            model_name='historicalentry',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalentry',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Datum'),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Datum'),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('organisation', 'date')]),
        ),
    ]
