# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20160601_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name=b'Visum Werkstattchef'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalentry',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name=b'Visum Werkstattchef'),
            preserve_default=False,
        ),
    ]
