# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20170728_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name=b'Visum Werkstattchef'),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name=b'Visum Werkstattchef'),
        ),
    ]
