# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import velafrica.core.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploadzeitpunkt')),
                ('name', models.CharField(help_text='Name der im Frontend angezeigt werden soll', max_length=255, verbose_name='Dateiname')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung')),
                ('file', models.FileField(blank=True, help_text='Select file to upload.', null=True, storage=velafrica.core.storage.MyStorage(), upload_to='downloads/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploadzeitpunkt')),
                ('name', models.CharField(help_text='Name der im Frontend angezeigt werden soll', max_length=255, verbose_name='Dateiname')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung')),
                ('file', models.TextField(blank=True, help_text='Select file to upload.', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical file',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
