# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 11:44
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20160531_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Uploadzeitpunkt'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Uploadzeitpunkt'),
        ),
    ]
