# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20160601_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_parent',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='category_parent',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
    ]
