# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'organisation', '0001_initial'), (b'organisation', '0002_auto_20160129_1010'), (b'organisation', '0003_auto_20160202_1454'), (b'organisation', '0004_auto_20160218_0856'), (b'organisation', '0005_auto_20160609_1624'), (b'organisation', '0006_auto_20160609_1626'), (b'organisation', '0007_auto_20160610_1500'), (b'organisation', '0008_auto_20160610_1536'), (b'organisation', '0009_auto_20160610_1608'), (b'organisation', '0010_auto_20160611_0938'), (b'organisation', '0011_municipality'), (b'organisation', '0012_auto_20160611_0950'), (b'organisation', '0013_auto_20160708_1530'), (b'organisation', '0014_auto_20160722_1712'), (b'organisation', '0015_auto_20160725_0904'), (b'organisation', '0016_auto_20160728_1847'), (b'organisation', '0017_auto_20160729_0848'), (b'organisation', '0018_auto_20160729_1100'), (b'organisation', '0019_auto_20160729_1457'), (b'organisation', '0020_auto_20160729_1715'), (b'organisation', '0021_auto_20160802_1751'), (b'organisation', '0022_auto_20160809_2049')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrganisation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name=b'Name der Organisation')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strasse')),
                ('plz', models.IntegerField(blank=True, null=True, verbose_name=b'PLZ')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Ort')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson')),
                ('description', models.TextField(blank=True, null=True)),
                ('org_type', models.CharField(choices=[(b'vpn', b'Velorecyclingnetz Schweiz'), (b'other', b'Andere'), (b'africa', b'Partner Velafrica S\xc3\xbcd (Afrika)')], default=b'other', max_length=20, verbose_name=b'Organisations Typ')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical organisation',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name der Organisation')),
                ('street', models.CharField(max_length=255, verbose_name=b'Strasse')),
                ('plz', models.IntegerField(verbose_name=b'PLZ')),
                ('city', models.CharField(max_length=255, verbose_name=b'Ort')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Website')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Arbeitgeber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Django User Account')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='city',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Name der Organisation'),
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='street',
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Django User Account'),
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name des Kantons')),
                ('short', models.CharField(max_length=2, unique=True, verbose_name=b'K\xc3\xbcrzel der Gemeinde')),
            ],
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strasse und Hausnummer')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name=b'Zipcode / PLZ')),
                ('city', models.CharField(max_length=255, verbose_name=b'Ort')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Kanton / Region')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Name des Landes')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='L\xe4ndercode (ISO 3166-1 alpha-2)')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact',
            field=models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Country', verbose_name=b'Land'),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Address'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name=b'Adresse'),
        ),
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='org_type',
        ),
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='street',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Ort'),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Facebook Page (URL)'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Facebook Page (URL)'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website (URL)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website (URL)'),
        ),
    ]
