# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strasse und Hausnummer')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name=b'Zipcode / PLZ')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Ort')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Kanton / Region')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Name des Landes')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='L\xe4ndercode (ISO 3166-1 alpha-2)')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrganisation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name=b'Name der Organisation')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website (URL)')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Facebook Page (URL)')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Erstellt am'), ('~', 'Ge\xe4ndert'), ('-', 'Deleted')], max_length=1)),
                ('address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Address')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical organisation',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name=b'Name der Organisation')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website (URL)')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Facebook Page (URL)')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name=b'Adresse')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Arbeitgeber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Django User Account')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Country', verbose_name=b'Land'),
        ),
    ]
