# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Country', verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kanton / Region'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Strasse und Hausnummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zipcode / PLZ'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name des Landes'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='contact',
            field=models.TextField(blank=True, help_text='Name, Email, Telefon, Skype etc', null=True, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Page (URL)'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name der Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website (URL)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contact',
            field=models.TextField(blank=True, help_text='Name, Email, Telefon, Skype etc', null=True, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Page (URL)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name der Organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website (URL)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name='Arbeitgeber'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django User Account'),
        ),
    ]
