# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-02 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20170729_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canton',
        ),
    ]
