# Generated by Django 2.1.15 on 2020-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add email, phone and contact_person fields.
    """
    replaces = [('organisation', '0004_auto_20200122_1030'),
                ('organisation', '0005_auto_20200123_1324'),
                ('organisation', '0004_auto_20200122_1030_squashed_0005_auto_20200123_1324')
                ]

    dependencies = [
        ('organisation', '0003_auto_20190925_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel Nr.'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel Nr.'),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kontaktperson'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kontaktperson'),
        ),
    ]
