# Generated by Django 2.1.15 on 2020-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add email, phone and contact_person fields.
    """
    dependencies = [
        ('organisation', '0003_auto_20190925_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel Nr.'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tel Nr.'),
        ),
    ]
