# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20160218_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name des Kantons')),
                ('short', models.CharField(max_length=2, unique=True, verbose_name=b'K\xc3\xbcrzel der Gemeinde')),
            ],
        ),
        migrations.CreateModel(
            name='Muncipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name der Gemeinde')),
                ('gdenr', models.IntegerField(unique=True, verbose_name=b'Gemeindenr. des BFS')),
                ('name_short', models.CharField(max_length=255, verbose_name=b'Name der Gemeinde (kurz)')),
                ('plz', models.IntegerField(verbose_name=b'Postleitzahl')),
                ('plz_name', models.CharField(max_length=255, verbose_name=b'Name der Gemeinde (Post)')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Canton')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Website'),
        ),
    ]
