# Generated by Django 2.1.15 on 2020-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20200122_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kontaktperson'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='contact',
            field=models.TextField(blank=True, help_text='Name, Email, Telefon, Skype etc', null=True, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contact',
            field=models.TextField(blank=True, help_text='Name, Email, Telefon, Skype etc', null=True, verbose_name='Kontaktperson'),
        ),
    ]
