# Generated by Django 2.1.15 on 2020-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('organisation', '0005_auto_20200324_1137.py'), ]

    dependencies = [
        ('organisation', '0004_add_fields_email_phone_contact-person.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganisation',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Info Kontakt'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Info Kontakt'),
        ),
    ]
