# Generated by Django 2.1.15 on 2020-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Alter contact field description.
    """

    dependencies = [
        ('organisation', '0005_alter_field_contact-description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kontaktperson'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kontaktperson'),
        ),
    ]
