# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_auto_20160610_1608'),
    ]

    operations = [
    ]
