# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20160611_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdenr', models.IntegerField(verbose_name=b'Gemeindenr. des BFS')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name der Gemeinde')),
                ('name_short', models.CharField(max_length=255, verbose_name=b'Name der Gemeinde (kurz)')),
                ('plz', models.IntegerField(verbose_name=b'Postleitzahl')),
                ('plz_name', models.CharField(max_length=255, verbose_name=b'Name der Gemeinde (Post)')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Canton')),
            ],
        ),
    ]
