# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 07:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # TODO: delete
    dependencies = [
        ('organisation', '0010_auto_20160611_0938'),
    ]

    operations = [
    ]
