# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_municipality'),
    ]

    operations = [
    ]
