# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    #TODO: delete
    dependencies = [
        ('organisation', '0012_auto_20160611_0950'),
    ]

    operations = [
    ]
