# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_auto_20160708_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Strasse und Hausnummer')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name=b'Zipcode / PLZ')),
                ('city', models.CharField(max_length=255, verbose_name=b'Ort')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Kanton / Region')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name=b'L\xc3\xa4ngengrad')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name des Landes')),
                ('code', models.CharField(max_length=255, verbose_name=b'L\xc3\xa4ndercode (ISO 3166-1 alpha-2)')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='contact',
            field=models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson'),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='org_type',
            field=models.CharField(choices=[(b'vpn', b'Velorecyclingnetz Schweiz'), (b'other', b'Andere'), (b'africa', b'Partner Velafrica S\xc3\xbcd (Afrika)')], default=b'other', max_length=20, verbose_name=b'Organisations Typ'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact',
            field=models.TextField(blank=True, help_text=b'Name, Email, Telefon, Skype etc', null=True, verbose_name=b'Kontaktperson'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_type',
            field=models.CharField(choices=[(b'vpn', b'Velorecyclingnetz Schweiz'), (b'other', b'Andere'), (b'africa', b'Partner Velafrica S\xc3\xbcd (Afrika)')], default=b'other', max_length=20, verbose_name=b'Organisations Typ'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Country', verbose_name=b'Land'),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisation.Address'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name=b'Adresse'),
        ),
    ]
