# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    #TODO: delete
    dependencies = [
        ('organisation', '0014_auto_20160722_1712'),
    ]

    operations = [
    ]
