# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_auto_20160725_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='org_type',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='org_type',
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='city',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Ort'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='plz',
            field=models.IntegerField(blank=True, help_text=b'WARNING: Will be removed soon', null=True, verbose_name=b'PLZ'),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='street',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Strasse'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Ort'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='plz',
            field=models.IntegerField(blank=True, help_text=b'WARNING: Will be removed soon', null=True, verbose_name=b'PLZ'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='street',
            field=models.CharField(blank=True, help_text=b'WARNING: Will be removed soon', max_length=255, null=True, verbose_name=b'Strasse'),
        ),
    ]
