# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_auto_20160802_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='L\xe4ndercode (ISO 3166-1 alpha-2)'),
        ),
    ]
