# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160609_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionevent',
            name='additional_results',
            field=models.TextField(blank=True, help_text=b'Zus\xc3\xa4tzliche Resultate / Erkenntnisse'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='host',
            field=models.CharField(blank=True, help_text=b'Veranstalter des Sammelanlasses', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='hours_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='notes',
            field=models.TextField(blank=True, help_text=b'Weitere Infos / Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='people_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='pickup',
            field=models.CharField(blank=True, help_text=b'Infos zur Abholung der Velos', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='presence_velafrica',
            field=models.CharField(blank=True, help_text=b'Infos zur Pr\xc3\xa4senz von Velafrica am Event', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='processing',
            field=models.CharField(help_text=b'Infos zur Verarbeitung der gesammelten Velos', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='time',
            field=models.CharField(blank=True, help_text=b'Zeit f\xc3\xbcr Veloannahme', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='velo_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='website',
            field=models.URLField(blank=True, help_text=b'Website des Events'),
        ),
        migrations.AlterField(
            model_name='collectioneventtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
