# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_event_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionevent',
            name='additional_results',
            field=models.TextField(blank=True, help_text='Zusätzliche Resultate / Erkenntnisse, mündlichesFeedback, etc', verbose_name='weitere Resultate'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='address_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection',
            field=models.TextField(blank=True, help_text='Infos zur Abholung der Velos', verbose_name='Notizen Abtransport'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_confirmed',
            field=models.BooleanField(default=False, verbose_name='Transport bestätigt?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_other',
            field=models.CharField(blank=True, help_text='Wenn die Velos nicht von einem Velafrica Partner abgeholt werden, bitte hier eintragen von wem', max_length=255, verbose_name='Abtransport durch andere Organisation'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_vrn',
            field=models.ForeignKey(blank=True, help_text='Velafrica Partner der die Velos abholt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_organisation', to='organisation.Organisation', verbose_name='Abtransport durch VRN Partner'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='feedback',
            field=models.BooleanField(default=False, verbose_name='Feedback eingeholt?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='hours_amount',
            field=models.IntegerField(default=0, help_text='Anzahl geleistete Stunden von allen Helfern zusammen', verbose_name='Geleistete Stunden'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='intermediate_store',
            field=models.BooleanField(default=False, verbose_name='Zwischenlagerung möglich?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='material_returned',
            field=models.BooleanField(default=False, verbose_name='Material retour?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='material_returned_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen zu Material Retournierung'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='money_amount',
            field=models.IntegerField(default=0, help_text='Betrag in CHF der am Event gesammelt wurde', verbose_name='Gesammeltes Geld'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='notes',
            field=models.TextField(blank=True, help_text='Sachen die noch zu erledigen sind / Weitere Infos / Bemerkungen', verbose_name='To do'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='people_amount',
            field=models.IntegerField(default=0, verbose_name='Anzahl Helfer vor Ort'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='presence_velafrica',
            field=models.BooleanField(default=False, verbose_name='Präsenz Velafrica?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='presence_velafrica_info',
            field=models.CharField(blank=True, help_text='Infos zur Präsenz von Velafrica am Event', max_length=255, verbose_name='Präsenz Velafrica'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='processing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_organisation', to='organisation.Organisation', verbose_name='Velo Verarbeitung'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='processing_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Velo Verarbeitung Notizen'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='public',
            field=models.BooleanField(default=False, help_text='Soll der Event auf der Webseite angezeigt werden?', verbose_name='Öffentlich'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='time',
            field=models.CharField(blank=True, help_text='Zeit für Veloannahme', max_length=255, verbose_name='Veloannahme'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='velo_amount',
            field=models.IntegerField(default=0, help_text='Anzahl gesammelter Velos', verbose_name='Anzahl Velos'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='website',
            field=models.URLField(blank=True, help_text='Website des Events'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='custom_lat',
            field=models.CharField(blank=True, max_length=255, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='custom_lon',
            field=models.CharField(blank=True, max_length=255, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name der Sammelstelle'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Optionale Textinfo'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='opening_time',
            field=models.TextField(blank=True, verbose_name='Öffnungszeiten'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='Abholservice'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='pickup_description',
            field=models.TextField(blank=True, verbose_name='Abholservice Beschreibung'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='sbb',
            field=models.BooleanField(default=False, verbose_name='SBB'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='temp',
            field=models.BooleanField(default=False, verbose_name='Temporär'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='temp_end',
            field=models.DateField(blank=True, null=True, verbose_name='Temporär Ende'),
        ),
        migrations.AlterField(
            model_name='dropoff',
            name='temp_start',
            field=models.DateField(blank=True, null=True, verbose_name='Temporär Start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_notes',
            field=models.TextField(blank=True, verbose_name='Genauer Standort'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.EventCategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(max_length=255, verbose_name='Veranstalter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.HostType', verbose_name='Veranstalter Typ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Interne Notizen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='event',
            name='yearly',
            field=models.BooleanField(default=False, verbose_name='Jährlich wiederkehrend?'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(help_text='Name der Kategorie', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hosttype',
            name='name',
            field=models.CharField(help_text='Name der Veranstalter Kategorie', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Erledigt?'),
        ),
    ]
