# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160610_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('time', models.CharField(blank=True, help_text=b'Zeit f\xc3\xbcr Veloannahme', max_length=255)),
                ('host', models.CharField(blank=True, help_text=b'Veranstalter des Sammelanlasses', max_length=255)),
                ('notes', models.TextField(blank=True, help_text=b'Weitere Infos / Bemerkungen')),
                ('presence_velafrica', models.CharField(blank=True, help_text=b'Infos zur Pr\xc3\xa4senz von Velafrica am Event', max_length=255)),
                ('pickup', models.CharField(blank=True, help_text=b'Infos zur Abholung der Velos', max_length=255)),
                ('processing', models.CharField(help_text=b'Infos zur Verarbeitung der gesammelten Velos', max_length=255)),
                ('organisation_done', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, help_text=b'Website des Events')),
                ('velo_amount', models.IntegerField(default=0)),
                ('people_amount', models.IntegerField(default=0)),
                ('hours_amount', models.IntegerField(default=0)),
                ('additional_results', models.TextField(blank=True, help_text=b'Zus\xc3\xa4tzliche Resultate / Erkenntnisse')),
            ],
        ),
        migrations.RenameModel(
            old_name='CollectionEventType',
            new_name='EventType',
        ),
        migrations.RenameModel(
            old_name='CollectionEventTask',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='CollectionEventTaskProgress',
            new_name='TaskProgress',
        ),
        migrations.RenameModel(
            old_name='CollectionEventTaskStatus',
            new_name='TaskStatus',
        ),
        migrations.RemoveField(
            model_name='collectionevent',
            name='ort',
        ),
        migrations.DeleteModel(
            name='CollectionEvent',
        ),
    ]
