# Generated by Django 2.1.12 on 2019-09-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190326_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionevent',
            name='address_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_vrn',
            field=models.ForeignKey(blank=True, help_text='Velafrica Partner der die Velos abholt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_organisation', to='organisation.Organisation', verbose_name='Abtransport durch VRN Partner'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='processing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_organisation', to='organisation.Organisation', verbose_name='Velo Verarbeitung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.HostType', verbose_name='Veranstalter Typ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Region', verbose_name='Region'),
        ),
    ]
