# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 07:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20160611_0950'),
        ('collection', '0004_auto_20160611_0936'),
    ]

    operations = [
    ]
