# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 09:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20160611_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='collectionpartner',
            new_name='collection_partner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organisation_done',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='collection_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='feedback',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.EventType'),
            preserve_default=False,
        ),
    ]
