# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20160611_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='CollectionEvent',
        ),
        migrations.RenameField(
            model_name='taskprogress',
            old_name='event',
            new_name='collection_event',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
