# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20160611_0950'),
        ('collection', '0008_auto_20160613_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('yearly', models.BooleanField(default=False, verbose_name=b'J\xc3\xa4hrlich wiederkehrend?')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='collectionevent',
            name='collection_partner',
        ),
        migrations.RemoveField(
            model_name='collectionevent',
            name='collection_type',
        ),
        migrations.RemoveField(
            model_name='collectionevent',
            name='type',
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='collection_partner_other',
            field=models.CharField(blank=True, help_text=b'Wenn die Velos nicht von einem Velafrica Partner abgeholt werden, bitte hier eintragen von wem', max_length=255),
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='collection_partner_vrn',
            field=models.ForeignKey(blank=True, help_text=b'Velafrica Partner der die Velos abholt', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='feedback',
            field=models.BooleanField(default=False, verbose_name=b'Feedback eingeholt?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='hours_amount',
            field=models.IntegerField(default=0, help_text=b'Anzahl geleistete Stunden von allen Helfern zusammen', verbose_name=b'Geleistete Stunden'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='people_amount',
            field=models.IntegerField(default=0, verbose_name=b'Anzahl Helfer vor Ort'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='velo_amount',
            field=models.IntegerField(default=0, verbose_name=b'Anzahl gesammelte Velos'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CollectionPartner',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.EventCategory'),
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.Event'),
            preserve_default=False,
        ),
    ]
