# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20160611_0950'),
        ('collection', '0010_auto_20160613_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionevent',
            name='host',
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_other',
            field=models.CharField(blank=True, help_text=b'Wenn die Velos nicht von einem Velafrica Partner abgeholt werden, bitte hier eintragen von wem', max_length=255, verbose_name=b'Abtransport durch andere Organisation'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_vrn',
            field=models.ForeignKey(blank=True, help_text=b'Velafrica Partner der die Velos abholt', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation', verbose_name=b'Abtransport durch VRN Partner'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='pickup',
            field=models.CharField(blank=True, help_text=b'Infos zur Abholung der Velos', max_length=255, verbose_name=b'Abtransport'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='presence_velafrica',
            field=models.CharField(blank=True, help_text=b'Infos zur Pr\xc3\xa4senz von Velafrica am Event', max_length=255, verbose_name=b'Pr\xc3\xa4senz Velafrica'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='processing',
            field=models.CharField(help_text=b'Infos zur Verarbeitung der gesammelten Velos', max_length=255, verbose_name=b'Velo Verarbeitung'),
        ),
    ]
