# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20160613_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionevent',
            name='additional_results',
            field=models.TextField(blank=True, help_text=b'Zus\xc3\xa4tzliche Resultate / Erkenntnisse', verbose_name=b'weitere Resultate'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='pickup',
            field=models.TextField(blank=True, help_text=b'Infos zur Abholung der Velos', verbose_name=b'Abtransport'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='presence_velafrica',
            field=models.TextField(blank=True, help_text=b'Infos zur Pr\xc3\xa4senz von Velafrica am Event', verbose_name=b'Pr\xc3\xa4senz Velafrica'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='processing',
            field=models.TextField(blank=True, help_text=b'Infos zur Verarbeitung der gesammelten Velos', verbose_name=b'Velo Verarbeitung'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='time',
            field=models.CharField(blank=True, help_text=b'Zeit f\xc3\xbcr Veloannahme', max_length=255, verbose_name=b'Veloannahme'),
        ),
    ]
