# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20160613_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionevent',
            name='presence_velafrica',
            field=models.BooleanField(default=False),
        ),
    ]
