# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_collectionevent_presence_velafrica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionevent',
            old_name='pickup',
            new_name='collection',
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_confirmed',
            field=models.BooleanField(default=False, verbose_name=b'Transport Partner best\xc3\xa4tigt?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='presence_velafrica',
            field=models.BooleanField(default=False, verbose_name=b'Pr\xc3\xa4senz Velafrica?'),
        ),
    ]
