# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20160620_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionevent',
            options={'verbose_name': 'Sammelanlass', 'verbose_name_plural': 'Sammelanl\xe4sse'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Event Kategorie', 'verbose_name_plural': 'Event Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='taskprogress',
            options={'verbose_name': 'Task Fortschritt', 'verbose_name_plural': 'Task Fortschritte'},
        ),
    ]
