# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_auto_20160622_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionevent',
            name='money_amount',
            field=models.IntegerField(default=0, help_text=b'Betrag in CHF der am Event gesammelt wurde', verbose_name=b'Gesammeltes Geld'),
        ),
    ]
