# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_collectionevent_money_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(help_text=b'Name der Kategorie', max_length=255),
        ),
    ]
