# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0020_auto_20160729_1715'),
        ('collection', '0020_auto_20160729_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name=b'Adresse'),
        ),
    ]
