# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 14:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_auto_20160802_1751'),
        ('collection', '0021_event_address_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionevent',
            options={'ordering': ['-date_start'], 'verbose_name': 'Sammelanlass', 'verbose_name_plural': 'Sammelanl\xe4sse'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='address_notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='municipality',
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='address_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name=b'Adresse'),
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='address_notes',
            field=models.TextField(blank=True),
        ),
    ]
