# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_auto_20160804_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name der Veranstalter Kategorie', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Veranstalter Kategorie',
                'verbose_name_plural': 'Veranstalter Kategorien',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='address_notes',
            field=models.TextField(blank=True, verbose_name=b'Genauer Standort'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(help_text=b'Name der Kategorie', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.HostType'),
        ),
    ]
