# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_auto_20160804_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.HostType', verbose_name=b'Veranstalter Typ'),
        ),
    ]
