# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_auto_20160808_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionevent',
            name='processing_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Velo Verarbeitung Notizen'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='presence_velafrica_info',
            field=models.CharField(blank=True, help_text=b'Infos zur Pr\xc3\xa4senz von Velafrica am Event', max_length=255, verbose_name=b'Pr\xc3\xa4senz Velafrica'),
        ),
    ]
