# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_auto_20160815_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionevent',
            name='complete',
            field=models.BooleanField(default=False, verbose_name=b'Abgeschlossen'),
        ),
    ]
