# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0022_auto_20160809_2049'),
        ('collection', '0029_auto_20160928_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name der Sammelstelle')),
                ('active', models.BooleanField(default=True, verbose_name=b'Aktiv')),
                ('sbb', models.BooleanField(default=False, verbose_name=b'SBB')),
                ('temp', models.BooleanField(default=False, verbose_name=b'Tempor\xc3\xa4r')),
                ('temp_start', models.DateField(blank=True, verbose_name=b'Tempor\xc3\xa4r Start')),
                ('temp_end', models.DateField(blank=True, verbose_name=b'Tempor\xc3\xa4r Ende')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name=b'Kontaktperson')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name=b'Telefonnummer')),
                ('opening_time', models.TextField(blank=True, verbose_name=b'\xc3\x96ffnungszeiten')),
                ('notes', models.TextField(blank=True, verbose_name=b'Optionale Textinfo')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Address', verbose_name=b'Adresse')),
            ],
            options={
                'verbose_name': 'Abgabstelle',
                'verbose_name_plural': 'Abgabstellen',
            },
        ),
    ]
