# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_dropoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoff',
            name='custom_lat',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Latitude'),
        ),
        migrations.AddField(
            model_name='dropoff',
            name='custom_lon',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Longitude'),
        ),
    ]
