# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_auto_20161004_2150'),
        ('collection', '0032_auto_20161005_1540'),
    ]

    operations = [
    ]
