# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0033_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoff',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name=b'Abholservice'),
        ),
        migrations.AddField(
            model_name='dropoff',
            name='pickup_description',
            field=models.TextField(blank=True, verbose_name=b'Abholservice Beschreibung'),
        ),
    ]
