# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0034_auto_20161101_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionevent',
            name='intermediate_store',
            field=models.BooleanField(default=False, verbose_name=b'Zwischenlagerung m\xc3\xb6glich?'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='collection_partner_confirmed',
            field=models.BooleanField(default=False, verbose_name=b'Transport best\xc3\xa4tigt?'),
        ),
    ]
