# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0036_auto_20170203_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionevent',
            name='material_returned',
            field=models.BooleanField(default=False, verbose_name=b'Material retour?'),
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='material_returned_notes',
            field=models.TextField(blank=True, null=True, verbose_name=b'Bemerkungen zu Material Retournierung'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='additional_results',
            field=models.TextField(blank=True, help_text=b'Zus\xc3\xa4tzliche Resultate / Erkenntnisse, m\xc3\xbcndlichesFeedback, etc', verbose_name=b'weitere Resultate'),
        ),
    ]
