# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-02 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0038_collectionevent_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionevent',
            name='public',
            field=models.BooleanField(default=False, help_text=b'Soll der Event auf der Webseite angezeigt werden?', verbose_name=b'Ver\xc3\xb6ffentlicht'),
        ),
    ]
